ISPN-9366 Cache.size optimizations (pt. 2)
infinispan/infinispan pull request #10112
Opened 2022-05-10 17:44 UTC by jabolina

https://issues.redhat.com/browse/ISPN-9366

* Created a method for the size in the Publisher* interface and classes.

* We query locally for the size and issue request to some of the remote
targets to do the same. With the returned value we sum everything.

* Change ComponentRegistry to create the LocalClusterPublisherManager,
only needed so the component is already started when used.

This relates to #10042

2022-05-10 20:04 UTC, wburns requested changes
I like the use of the composed type 👍

2022-05-10 20:04 UTC, wburns commented on core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java
> +            sizeComposedType(), s -> PublisherReducers.count().apply(s), s -> PublisherReducers.add().apply(s));
IIUC the transformer is not used in this case. I would suggest just setting it to null to confirm or even throwing an exception.

2022-05-10 20:04 UTC, wburns commented on core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java
> +         return KEY_COMPOSED.contextInvocation(segments, keysToInclude, ctx, transformer);
This shouldn't ever be used. If the user provides a context that is not empty we either have to skip the optimization or we could do the optimization for segments that aren't in the context. I would say for this PR just always disable the optimization if the context has any values.

2022-05-10 20:04 UTC, wburns commented on core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java
> +         return KEY_COMPOSED.localInvocation(parallelPublisher, segments, keysToInclude, keysToExclude,
This should use the SizeCommand as well I would expect.

2022-05-12 17:24 UTC, wburns commented on core/src/main/java/org/infinispan/interceptors/impl/ClusteringInterceptor.java
> +      return invokeNext(ctx, command);
I would expect this to look more like this. The `sizePublisher` would then pass the FLAG_MODE_LOCAL flag.

```suggestion
      if (isLocalModeForced(command) {
         return invokeNext(ctx, command);
      }
      if (command.hasAnyFlag(FlagBitSets.SKIP_SIZE_OPTIMIZATION)) {
         return asyncValue(clusterPublisherManager.keyReduction(false, null, null, ctx,
               command.getFlagsBitSet(), DeliveryGuarantee.EXACTLY_ONCE, PublisherReducers.count(),
               PublisherReducers.add()));
      }

      return asyncValue(clusterPublisherManager.sizePublisher(command.getSegments(), ctx, command.getFlagsBitSet()));
```

2022-05-12 17:24 UTC, wburns commented on core/src/main/java/org/infinispan/reactive/publisher/impl/LocalPublisherManagerImpl.java
> +      if (!EnumUtil.containsAny(flags, FlagBitSets.CACHE_MODE_LOCAL)) {
This if shouldn't be needed afai can tell.

2022-05-12 17:24 UTC, wburns commented on core/src/main/java/org/infinispan/interceptors/impl/ClusteringInterceptor.java
> +      return invokeNext(ctx, command);
I am not sure why the usingStores was referenced. We should be able to do the optimization with or without stores.

2022-05-12 20:36 UTC, jabolina commented on core/src/main/java/org/infinispan/container/impl/InternalDataContainer.java
> +         if (iter.next().getValue() == null) continue;
because of the scattered mode

2022-05-13 18:28 UTC, jabolina commented
Moved everything to #10042

2022-05-13 18:28 UTC, closed without merging