ISPN-13922 Fix SslTest on Windows
infinispan/infinispan pull request #10147
Opened 2022-05-25 15:12 UTC by tristantarrant

https://issues.redhat.com/browse/ISPN-13922

2022-06-09 11:15 UTC, ryanemerson requested changes

2022-06-09 11:15 UTC, ryanemerson commented on client/hotrod-client/src/test/java/org/infinispan/client/hotrod/SslTest.java
> +      Exceptions.expectExceptionNonStrict(TransportException.class, DecoderException.class, () -> initServerAndClient(true, true, true, false, false, false));
This is failing, as a `ClosedChannelException` is being thrown instead of the `DecoderException`.

2022-07-05 12:01 UTC, tristantarrant commented
No, those were fixed in https://github.com/infinispan/infinispan/pull/10186

2022-07-05 13:09 UTC, merged

2022-07-05 13:10 UTC, ryanemerson commented
I see! Thanks @tristantarrant