[14.0] ISPN-14016 Implement HotRodMutinyCaches methods
infinispan/infinispan pull request #10529
Opened 2022-12-07 13:09 UTC by jabolina

https://issues.redhat.com/browse/ISPN-14016

Only adding the methods here. The backport of tests is not easy, as we have a few commits creating all the structure.

2022-12-07 17:22 UTC, wburns requested changes

2022-12-07 17:22 UTC, wburns commented on client/hotrod/src/main/java/org/infinispan/hotrod/HotRodMutinyCaches.java
> +   private Multi<String> toMulti(CompletionStage<Set<String>> cs) {
This can just be `return Multi.createFrom().completionStage(cs).onItem().transformToIterable(Function.identity());`

2022-12-07 17:22 UTC, wburns commented on client/hotrod/src/main/java/org/infinispan/hotrod/HotRodMutinyCaches.java
> +      return Uni.createFrom().completionStage(hotrod.transport.<K, V>getRemoteCache(name))
Technically Uni should be completely lazy, that is the operation isn't performed until subscribed. We may want to use the Supplier completionStage method to be 100% safe.

2022-12-08 09:26 UTC, karesti approved these changes

2022-12-08 09:26 UTC, merged