ISPN-14492 Java 17 instead of 11
infinispan/infinispan pull request #10612
Opened 2023-02-01 10:13 UTC by karesti

https://issues.redhat.com/browse/ISPN-14492

2023-02-01 10:21 UTC, tristantarrant commented
Please update the contribution guide too.

2023-02-01 10:41 UTC, karesti commented
@tristantarrant guide updated

2023-02-01 11:00 UTC, tristantarrant commented on documentation/src/main/asciidoc/topics/ref_quick_start.adoc
> +* Java 17 JDK at a minimum. {brandname} also works with 18, 19.
We will still build for JDK 11

2023-02-01 14:17 UTC, karesti commented on documentation/src/main/asciidoc/topics/ref_quick_start.adoc
> +* Java 17 JDK at a minimum. {brandname} also works with 18, 19.
fixed again

2023-02-08 11:06 UTC, pruivo requested changes

2023-02-08 11:06 UTC, pruivo commented on documentation/src/main/asciidoc/topics/proc_adding_hotrod_client_dependencies.adoc
> +* Java 8, Java 11 or Java 17
I believe we dropped Java 8 in ISPN 14+
```suggestion
* Java 11 or greater.
```

2023-02-08 11:06 UTC, pruivo commented on documentation/src/main/asciidoc/topics/ref_quick_start.adoc
> +* Java 11 JDK at a minimum. {brandname} also works with 17, 18, 19.
```suggestion
* Java 11 JDK at a minimum.
```
AFAIK, we don't test with JDK 18/19. Speaking of testing, we may need a profile to test with JDK 11, right? 
cc @tristantarrant wdyt? is it worth adding such complexity?

2023-02-10 10:05 UTC, karesti commented
@pruivo I added your changes

2023-02-10 14:48 UTC, pruivo approved these changes

2023-02-10 14:56 UTC, merged

2023-02-10 14:56 UTC, tristantarrant commented
Merged, thanks