ISPN-14552 REST API to reset stats
infinispan/infinispan pull request #10683
Opened 2023-03-07 13:03 UTC by tristantarrant

https://issues.redhat.com/browse/ISPN-14552

2023-03-13 16:56 UTC, jabolina requested changes

2023-03-13 16:56 UTC, jabolina commented on client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheClientOkHttp.java
> +      builder.method("POST",new FormBody.Builder().build()).url(cacheUrl + "?action=stats-reset").get();
The `.get()` at the end is changing the request type.

```suggestion
      builder.method("POST",new FormBody.Builder().build()).url(cacheUrl + "?action=stats-reset");
```

2023-03-13 16:56 UTC, jabolina commented on server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java
> +         assertStatus(OK, cache.statsReset());
```suggestion
         assertStatus(NO_CONTENT, cache.statsReset());
```

2023-03-14 11:13 UTC, tristantarrant commented
I've applied your changes

2023-03-14 14:10 UTC, merged

2023-03-14 14:11 UTC, jabolina commented
Integrated into main, thanks @tristantarrant!