ISPN-14572 Sping 6 and SB 3 docs
infinispan/infinispan pull request #10747
Opened 2023-03-29 15:17 UTC by dvagnero

https://issues.redhat.com/browse/ISPN-14572
needs backport to 14

- update dependencies
- add info that spring 6 and SB 3 require Java 17

2023-03-30 07:29 UTC, karesti requested changes
I think we still need to keep track on the 2.x and Spring 5 before the support is removed

2023-03-30 07:41 UTC, karesti commented
@dvagnero you changed the dependencies so if someone wants to start with spring 2.x using infinispan, they don't have the dependencies and names are different

2023-03-30 14:57 UTC, dvagnero commented
@karesti I added note with "old" dependencies. I hope this works. Backport is ready here https://github.com/infinispan/infinispan/pull/10755

2023-03-31 13:48 UTC, karesti approved these changes

2023-03-31 13:48 UTC, merged