ISPN-14575 Remove properties attribute from indexing configuration
infinispan/infinispan pull request #10758
Opened 2023-03-31 10:24 UTC by fax4ever

https://issues.redhat.com/browse/ISPN-14575

and the two it depends on:
https://issues.redhat.com/browse/ISPN-14722
https://issues.redhat.com/browse/ISPN-14723

2023-04-12 10:42 UTC, tristantarrant commented
Instead of the dychotomy of `autoIndexing` and `manualIndexing` using booleans, I'd prefer the use of an enum `IndexingMode` with `MANUAL` and `AUTO` values for now.

2023-04-12 10:46 UTC, tristantarrant requested changes

2023-04-12 10:46 UTC, tristantarrant commented on core/src/main/java/org/infinispan/util/logging/Log.java
> -   @LogMessage(level = WARN)
Instead of removing this code, use a block-comment. This reminds us why there is a gap in the logging IDs.

2023-04-12 10:49 UTC, fax4ever commented
> Instead of the dychotomy of `autoIndexing` and `manualIndexing` using booleans, I'd prefer the use of an enum `IndexingMode` with `MANUAL` and `AUTO` values for now.

it looks a good idea, I'm going to apply it

2023-04-12 12:59 UTC, fax4ever commented
Thanks for the review @tristantarrant.
Did the changes.

2023-04-12 14:16 UTC, fax4ever commented
@tristantarrant I also added this commit https://github.com/infinispan/infinispan/pull/10758/commits/2ca9c49a36bfa98707a67ae755f83eae5f529aa7 to review the remaining deprecated / undocumented property

2023-04-14 06:00 UTC, tristantarrant commented on core/src/main/java/org/infinispan/configuration/cache/IndexingMode.java
> +      return Arrays.stream(IndexingMode.values())
Easier to do:

```java
try {
return IndexingMode.valueOf(value.toUpperCase());
} catch (IllegalArgumentException e) {
   throw Log.CONFIG.illegalEnumValue(value, EnumSet.allOf(IndexingMode.class));
}
```

2023-04-14 06:01 UTC, tristantarrant commented on core/src/main/java/org/infinispan/configuration/cache/IndexShardingConfiguration.java
> +   public static final AttributeDefinition<Integer> NUMBER_OF_SHARDS =
I think it would nicer to rename this to `SHARDS` everywhere

2023-04-14 06:02 UTC, tristantarrant requested changes
A couple more changes, please

2023-04-14 09:04 UTC, fax4ever commented
> A couple more changes, please

Good ideas. I applied the changes

2023-04-14 10:52 UTC, merged

2023-04-14 10:52 UTC, tristantarrant commented
Merged, thanks

2023-04-14 10:57 UTC, fax4ever commented
Thanks @tristantarrant