ISPN-14724 Define a builder helper to define custom proto schema
infinispan/infinispan pull request #10761
Opened 2023-03-31 18:16 UTC by fax4ever

https://issues.redhat.com/browse/ISPN-14724

2023-04-01 06:39 UTC, tristantarrant commented
I would put this in the infinispan-api module so it can be used in both embedded and remote deployments

2023-04-01 07:38 UTC, fax4ever commented
Moved to the api module and added a real test.

2023-04-04 10:07 UTC, tristantarrant requested changes

2023-04-04 11:59 UTC, fax4ever commented on core/src/test/java/org/infinispan/marshall/protostream/builder/ProtoBufBuilderTest.java
> +      assertThat(proto).isNotBlank();
This file was supposed to be deleted, but I forgot to do that. I removed it.
The process is tested in the HotRod client module using our validation system and I just added the file comparison.

2023-04-04 12:00 UTC, fax4ever commented
Thanks @tristantarrant, I think I fixed it.

2023-04-14 12:17 UTC, merged

2023-04-14 12:17 UTC, tristantarrant commented
Merged, thanks

2023-04-14 13:19 UTC, fax4ever commented
Thank you