WIP:ISPN-14008 docs updates new annotations and startup mode
infinispan/infinispan pull request #10785
Opened 2023-04-04 17:22 UTC by dvagnero

https://issues.redhat.com/browse/ISPN-14008
Infinispan indexing annotations
needs backport to 14

2023-04-04 17:23 UTC, dvagnero commented on documentation/src/main/asciidoc/topics/code_examples/AnalyzerDefinitions.java
> -@Field(store = Store.YES, analyze = Analyze.YES, analyzer = @Analyzer(definition = "keyword"))
@fax4ever could you please review the examples?

2023-04-05 13:34 UTC, fax4ever reviewed
@dvagnero I reviewed the examples

2023-04-05 13:50 UTC, fax4ever commented on documentation/src/main/asciidoc/topics/con_indexing_annotations.adoc
> +|Attribute |Description |Values | Annotation
|            | searchable | sortable | projectable | aggregable | indexNullAs | decimalScale | normalizer | norms | analyzer | searchAnalyzer | termVector |
|------------|------------|----------|-------------|------------|-------------|--------------|------------|-------|----------|----------------|------------|
| `@Basic`   | yes        | yes      | yes         | yes        | yes         | no           | no         | no    | no       | no             | no         |
| `@Decimal` | yes        | yes      | yes         | yes        | yes         | yes          | no         | no    | no       | no             | no         |
| `@Keyword` | yes        | yes      | yes         | yes        | yes         | no           | yes        | yes   | no       | no             | no         |
| `@Text`    | yes        | no       | yes         | no         | no          | no           | no         | yes   | yes      | yes            | yes        |

2023-04-07 14:12 UTC, fax4ever reviewed
Thank you @dvagnero I reviewed the rest.
Nice job, only a comment here.

In the previous review https://github.com/infinispan/infinispan/pull/10785#pullrequestreview-1372823376, you can find the review of the examples.

2023-05-16 15:03 UTC, dvagnero commented on documentation/src/main/asciidoc/topics/con_indexing_annotations.adoc
> +|Attribute |Description |Values | Annotation
Thank you @fax4ever I updated the table and descriptions of annotations. I'll check the procedures and examples tomorrow. 
Do we need some description for attributes?

2023-05-17 10:18 UTC, fax4ever requested changes
I think that the suggestions are not properly applied

2023-05-18 09:41 UTC, fax4ever approved these changes

2023-05-18 09:42 UTC, fax4ever commented
Thank you @dvagnero. Great job here!
Going to merge it.

2023-05-18 09:42 UTC, merged