RESP Incrby decrby operations
infinispan/infinispan pull request #10873
Opened 2023-04-27 15:35 UTC by rigazilla

Implementation and test.
Based on #10855

2023-04-28 09:25 UTC, karesti requested changes

2023-04-28 09:25 UTC, karesti commented on server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
> +      assertEquals(42L, newValue.longValue());
refactor to use assertJ

2023-05-02 13:01 UTC, rigazilla commented on server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
> +      assertEquals(42L, newValue.longValue());
@karesti you didn't press the button :)

2023-05-02 14:08 UTC, karesti approved these changes

2023-05-02 14:08 UTC, merged

2023-05-03 15:19 UTC, wburns commented
@rigazilla Next time make sure the commit message starts with the JIRA id, thanks!