ISPN-14880 RESP DBSIZE
infinispan/infinispan pull request #10956
Opened 2023-05-17 13:26 UTC by tristantarrant

https://issues.redhat.com/browse/ISPN-14880

2023-05-17 19:37 UTC, karesti requested changes

2023-05-17 19:37 UTC, karesti commented on server/resp/src/main/java/org/infinispan/server/resp/commands/connection/DBSIZE.java
> +      super(0, 0, 0, 0);
arity is 1

2023-05-17 19:37 UTC, karesti commented on server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
> +      assertThat(redis.dbsize()).isEqualTo(cache.size());
we should test a value set and comparing the size

2023-05-18 03:31 UTC, tristantarrant commented
Fixed the issues

2023-05-19 13:19 UTC, jabolina approved these changes
LGTM, but needs a rebase.

2023-05-19 13:20 UTC, tristantarrant commented
Rebased

2023-05-19 22:18 UTC, wburns approved these changes
LGTM

2023-05-22 12:09 UTC, karesti approved these changes

2023-05-22 12:09 UTC, merged