ISPN-14872 Include RESP in AbstractAuthorization tests
infinispan/infinispan pull request #10961
Opened 2023-05-17 15:25 UTC by jabolina

https://issues.redhat.com/browse/ISPN-14872

Besides adding the tests with the server authorization, this also includes a way to authenticate using a certificate. The only thing not covered is Kerberos, which is skipped.

2023-05-18 05:54 UTC, tristantarrant requested changes
I would really like to split `AbstractAuthorization` into per-protocol classes and turn the various `*AuthorizationIT` classes into `Suite`s.

2023-05-18 05:54 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/Resp3AuthHandler.java
> +         return success ? CompletableFutures.completedTrue() : CompletableFutures.completedFalse();
The original code was better :)

2023-05-18 05:54 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/Resp3AuthHandler.java
> +      if (username == null && password == null) {
Probably you should also check `authenticator.isClientCertAuthEnabled()` here

2023-05-18 05:54 UTC, tristantarrant commented on server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointConfigurationBuilder.java
>              throw Server.log.respEndpointRequiresRealmWithPassword();
Change the log to also say "or a truststore realm"

2023-05-18 05:54 UTC, tristantarrant commented on server/runtime/src/main/java/org/infinispan/server/security/RespClientCertAuthenticator.java
> +      SaslAuthenticator sap = new SimpleSaslAuthenticator();
You should not be using the `SimpleSaslAuthenticator` but rather rely on the Elytron SASL authenticator which has been configured with a `TrustStoreRealm` and therefore can validate the client certificates against the trust store.

2023-05-18 19:53 UTC, jabolina commented
Applied all the suggestions. Since we have the command `INFO`, I added a test for it, meaning slight changes, storing the subject with an attribute key and the permission check.

Now, I'll focus on trying to split the tests per protocol. But the other parts are ready for review again.

2023-05-19 07:25 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java
> +      SecurityActions.checkPermission(respServer.getCacheManager(), subject, authorizationPermission);
This code is wrong. 
Some authz checks need to be done against the cache permissions, while others may need to be done using the global permissions.

2023-05-23 18:38 UTC, jabolina commented
Fixed the previous issues. Some resources were leaking after the test was finished. But now Lettuce threads are leaking.

2023-05-24 12:00 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/Resp3AuthHandler.java
> +   static final AttributeKey<Subject> SUBJECT_ATTRIBUTE_KEY = AttributeKey.newInstance("subject");
@jabolina I'm adding the Subject to the `ConnectionMetadata` in https://github.com/infinispan/infinispan/pull/10964

2023-05-24 13:52 UTC, jabolina commented
Updated removing the Subject attr key. The last CI run had a [failure in the REST backup test](https://ci.infinispan.org/job/Infinispan/job/PR-10961/8/testReport/org.infinispan.server.security.authorization/RESTAuthorizationTest/testRestAdminsMustAccessBackupsAndRestores/).

This was triggered by running the RESP tests first, and since the `respCache` would have heterogeneous entries, plain `byte[]` and multimap objects, the test would fail. I added a little workaround checking the metadata, but that's until we establish a way to verify the entries properly for data structures.

2023-05-24 15:21 UTC, jabolina commented
Looks like I broke everything again.

2023-05-24 18:35 UTC, jabolina commented
Well, the thread dump had almost 300 Ok Http threads, and the CI logs have some hints about that, too. I took some time removing all usages of `sync` in the REST tests, which could leak some resources. Let's see how it goes.

2023-05-25 18:33 UTC, jabolina commented
Looks like the failures are unrelated.

2023-05-29 07:43 UTC, tristantarrant approved these changes

2023-05-29 07:43 UTC, merged

2023-05-29 07:47 UTC, tristantarrant commented
Merged, thanks