ISPN-14632 LPOS command
infinispan/infinispan pull request #10997
Opened 2023-05-29 15:01 UTC by karesti

https://issues.redhat.com/browse/ISPN-14632

2023-05-30 13:39 UTC, jabolina requested changes
Just one thing. Later, we can also change the long collection to avoid allocating strings.

2023-05-31 09:40 UTC, karesti commented
@jabolina rebase done

2023-05-31 12:16 UTC, jabolina approved these changes

2023-05-31 12:18 UTC, jabolina commented
Looks like there's a related failure in CI.

2023-05-31 15:28 UTC, merged