ISPN-14665 HINCRBY commands
infinispan/infinispan pull request #11080
Opened 2023-06-30 17:11 UTC by jabolina

https://issues.redhat.com/browse/ISPN-14665

This includes `HINCRBY` and `HINCRBYFLOAT`. I added a `compute(key, property, biConsumer)` to implement both incr methods.

2023-07-03 14:39 UTC, rigazilla requested changes
lgtm, .adoc missing?

2023-07-03 18:07 UTC, jabolina commented
Looks like I've missed all the docs :sweat_smile: Updated.

2023-07-07 13:24 UTC, karesti approved these changes

2023-07-11 18:31 UTC, karesti approved these changes

2023-07-11 18:31 UTC, merged