ISPN-14924 Retrieve roles and permissions
infinispan/infinispan pull request #11326
Opened 2023-09-26 12:15 UTC by karesti

2023-09-26 12:25 UTC, karesti commented
@tristantarrant is there a way to know which are the pre defined roles?

2023-09-26 16:15 UTC, karesti commented
@tristantarrant I have my answer, I'm adding the enhancement

2023-09-26 17:23 UTC, tristantarrant requested changes
We need a test in `RESTAuthorizationTest`

2023-09-27 14:57 UTC, karesti commented on server/testdriver/core/src/main/java/org/infinispan/server/test/core/Containers.java
> +            return "amd64";
I opened a separate PR

2023-09-28 12:44 UTC, karesti commented
@tristantarrant I added the tests

2023-10-06 09:19 UTC, ryanemerson requested changes
@karesti The following failures seem related:

```
[org.infinispan.server.security.authorization.AuthorizationKerberosIT$Rest.testRoleManipulation](https://ci.infinispan.org/job/Infinispan/job/PR-11326/5/testReport/junit/org.infinispan.server.security.authorization/AuthorizationKerberosIT$Rest/testRoleManipulation/)
[org.infinispan.server.security.authorization.AuthorizationKerberosIT$Rest.(?)](https://ci.infinispan.org/job/Infinispan/job/PR-11326/5/testReport/junit/org.infinispan.server.security.authorization/AuthorizationKerberosIT$Rest/___/)
[org.infinispan.server.security.authorization.AuthorizationLDAPIT$Rest.testRoleManipulation](https://ci.infinispan.org/job/Infinispan/job/PR-11326/5/testReport/junit/org.infinispan.server.security.authorization/AuthorizationLDAPIT$Rest/testRoleManipulation/)
[org.infinispan.server.security.authorization.AuthorizationPropertiesIT$Rest.testRoleManipulation](https://ci.infinispan.org/job/Infinispan/job/PR-11326/5/testReport/junit/org.infinispan.server.security.authorization/AuthorizationPropertiesIT$Rest/testRoleManipulation/)
```

2023-10-13 11:53 UTC, karesti commented
@ryanemerson should be good now

2023-10-16 13:45 UTC, karesti commented
relates to https://github.com/infinispan/infinispan-console/pull/413

2023-10-17 15:25 UTC, ryanemerson commented
The `org.infinispan.rest.resources.AccessManagementResourceTest.testDetailedRolesList` failures look related.

2023-10-17 15:46 UTC, karesti commented
@ryanemerson something I forgot to remove

2023-10-18 09:13 UTC, merged

2023-10-18 09:13 UTC, ryanemerson commented
Thanks @karesti