ISPN-15273 XSiteMBeanTest fails randomly
infinispan/infinispan pull request #11436
Opened 2023-10-26 13:36 UTC by pruivo

https://issues.redhat.com/browse/ISPN-15273

2023-10-26 14:25 UTC, karesti approved these changes

2023-10-26 14:26 UTC, karesti requested changes
can't be built ?

2023-10-26 17:58 UTC, pruivo commented
@karesti what error are you getting?

2023-10-27 09:11 UTC, karesti approved these changes

2023-10-27 09:11 UTC, merged