ISPN-15269 Create or Update a role
infinispan/infinispan pull request #11431
Opened 2023-10-25 14:07 UTC by karesti

2023-10-26 12:22 UTC, karesti commented
unrelated failures

2023-11-06 14:37 UTC, tristantarrant requested changes
Please modify `user.adoc` in the CLI help to include these changes.

2023-11-06 14:37 UTC, tristantarrant commented on cli/src/main/java/org/infinispan/cli/commands/rest/Roles.java
> +   @CommandDefinition(name = "update", description = "Updates an existing role")
You need to add `Roles.Update.class` to the `@GroupCommandDefinition` at the top

2023-11-08 09:12 UTC, tristantarrant commented
```
 FATAL [o.i.SERVER] ISPN080028: Infinispan Server failed to start org.infinispan.rest.framework.RegistrationException: ISPN012015: Cannot register invocation 'ROLES UPDATE': resource already registered for method 'PUT' at the destination path '/{role}'
 ```

2023-11-08 11:02 UTC, karesti commented
@tristantarrant green

2023-11-08 11:08 UTC, merged

2023-11-08 11:08 UTC, tristantarrant commented
Merged, thanks