ISPN-15824 Collect tls endpoing from protocol servers
infinispan/infinispan pull request #12089
Opened 2024-03-05 11:55 UTC by fax4ever

https://issues.redhat.com/browse/ISPN-15823
https://issues.redhat.com/browse/ISPN-15824

2024-03-05 12:53 UTC, tristantarrant requested changes

2024-03-05 12:53 UTC, tristantarrant commented on server/runtime/src/main/java/org/infinispan/server/Server.java
> +         if (realConfig.hasClientSSLContext()) {
This is wrong. Ignore the client context.
```java
        if (realmConfig.hasServerSSLContext()) {
            if (realmConfig.hasFeature(ServerSecurityRealm.Feature.TRUST)) {
               securityRealms.set(realm.getKey(), Json.object("tls", "CLIENT"));
            } else {
               securityRealms.set(realm.getKey(), Json.object("tls", "SERVER"));
            }
         } else {
            securityRealms.set(realm.getKey(), Json.object("tls", "NONE"));
         }
```

2024-03-05 13:23 UTC, fax4ever commented
Pushed the change, thanks @tristantarrant

2024-03-05 15:59 UTC, tristantarrant commented
I would like to see some tests in `AuthenticationTLSIT` (should return `CLIENT`) `TLSWithoutAuthenticationIT` (should return `SERVER`) and `OverviewReportIT` (should return `NONE`).

2024-03-06 07:57 UTC, merged

2024-03-06 07:57 UTC, tristantarrant commented
Merged, thanks

2024-03-06 08:36 UTC, fax4ever commented
Thank you @tristantarrant