ISPN-15933 HTTP compression/decompression
infinispan/infinispan pull request #12220
Opened 2024-03-29 11:26 UTC by tristantarrant

https://issues.redhat.com/browse/ISPN-15933

2024-04-02 18:00 UTC, pruivo requested changes

2024-04-02 18:00 UTC, pruivo commented on server/rest/src/main/java/org/infinispan/rest/configuration/RestServerConfigurationBuilder.java
> +   public RestServerConfigurationBuilder compressionThreshold(int compressThreshold) {
This new option is never parsed.

2024-04-03 05:04 UTC, tristantarrant commented on server/rest/src/main/java/org/infinispan/rest/configuration/RestServerConfigurationBuilder.java
> +   public RestServerConfigurationBuilder compressionThreshold(int compressThreshold) {
oops, fixed

2024-04-04 08:10 UTC, pruivo approved these changes

2024-04-10 10:16 UTC, merged

2024-04-10 10:16 UTC, pruivo commented
merged! thanks @tristantarrant !