ISPN-16092 Documenting RESP cache
infinispan/infinispan pull request #12412
Opened 2024-05-21 14:56 UTC by rigazilla

Docu has an unresolved ref that breaks part of the RESP docu, [see](https://infinispan.org/docs/15.0.x/titles/resp/resp-endpoint.html)
This is a fix.
Also some lines were replicated, I cleaned up a bit and made it similar to the REST docu structure.

fixes https://issues.redhat.com/browse/ISPN-16092

2024-05-22 08:36 UTC, theashiot approved these changes
LGTM, thanks!

2024-05-27 05:47 UTC, tristantarrant requested changes

2024-05-27 05:47 UTC, tristantarrant commented on documentation/src/main/asciidoc/titles/resp/resp-endpoint.asciidoc
> +Infinispan Server includes an endpoint that implements the link:https://github.com/redis/redis-specifications/blob/master/protocol/RESP3.md[RESP3 protocol] and allows you to interact with remote cach
Use {brandname}

2024-05-27 05:47 UTC, tristantarrant commented on documentation/src/main/asciidoc/topics/proc_server_configuring_resp.adoc
> += Infinispan RESP endpoint
{brandname}

2024-05-27 10:46 UTC, merged