ISPN-16170 Expose if tracing is enabled in the server
infinispan/infinispan pull request #12489
Opened 2024-06-10 10:22 UTC by karesti

2024-06-11 14:07 UTC, pruivo requested changes

2024-06-11 14:07 UTC, pruivo commented on core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
> +   public Boolean isTracingEnabled() {
why returning `Boolean` instead of `boolean`?

2024-06-11 14:07 UTC, pruivo commented on core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
> +      } catch (Exception e) {
what exception are you getting?

2024-06-11 14:07 UTC, pruivo commented on core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
> +      if (rebalancingEnabled != null) {
`rebalancingEnabled != null`? :smiley:

2024-06-12 10:35 UTC, karesti commented on core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
> +      } catch (Exception e) {
Probably nothing, I can clean up

2024-06-12 10:53 UTC, karesti commented
@pruivo I updated docs and fix. added on full detail as well the tracing

2024-06-12 17:10 UTC, merged

2024-06-12 17:10 UTC, pruivo commented
merged! thanks @karesti !