ISPN-16269 Export telemetry information with JFR
infinispan/infinispan pull request #12599
Opened 2024-07-03 13:21 UTC by jabolina

Just opening this as a draft so I can use it in the benchmarks.

FYI @fax4ever @pruivo 

It generates the events for JFR carrying the information from the span. For example:

![image](https://github.com/infinispan/infinispan/assets/13581903/7237dafd-4f1a-4098-aeb4-da2062a151b4)

This is to get an idea while running the benchmarks. Some information is still left out, like the category, node name, etc. The `Event` class of JFR accepts pretty much only primitives.

2024-07-03 13:39 UTC, infinispanrelease commented
Image pushed for Jenkins build [#1](https://ci.infinispan.org/job/Infinispan/job/PR-12599/1/):
```
quay.io/infinispan-test/server:PR-12599
```

2024-07-03 14:30 UTC, jabolina commented
For those interested, a JBang script to parse the generated JFR:

```java
///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS info.picocli:picocli:4.6.3
//DEPS org.hdrhistogram:HdrHistogram:2.2.2


import java.io.IOException;
import java.nio.file.Path;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.concurrent.Callable;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import org.HdrHistogram.Histogram;
import org.HdrHistogram.HistogramIterationValue;

import jdk.jfr.ValueDescriptor;
import jdk.jfr.consumer.RecordedEvent;
import jdk.jfr.consumer.RecordingFile;
import picocli.CommandLine;
import picocli.CommandLine.Command;

@Command(name = "JfrParser", mixinStandardHelpOptions = true, version = "JfrParser 0.1",
        description = "JfrParser made with jbang")
class JfrParser implements Callable<Integer> {

    private static final String ROOT_SPAN = "0000000000000000";
    private static final SimpleDateFormat SIMPLE_DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");

    @CommandLine.Option(names = "-files", split = ",", arity = "1..*")
    private String[] files;

    @CommandLine.Option(names = "-c", required = true)
    private String category;

    @CommandLine.Option(names = "-start")
    private Date after;

    @CommandLine.Option(names = "-end")
    private Date before;

    @CommandLine.Option(names = "-p", defaultValue = "false")
    private boolean percentiles;

    @CommandLine.Option(names = "-high", defaultValue = "0")
    private int highest;

    public static void main(String... args) {
        CommandLine cmd = new CommandLine(new JfrParser())
              .registerConverter(Date.class, SIMPLE_DATE_FORMAT::parse);
        int exitCode = cmd.execute(args);
        System.exit(exitCode);
    }

    @Override
    public Integer call() throws Exception {
        if (after != null)
            System.out.printf("Filter for after %s\n", after);

        if (before != null) {
            System.out.printf("Filter for before %s\n", before);
        }

        List<Span> spans = read().toList();
        Tree tree = createTree(spans);

        Histogram global = showRootMetrics(tree.roots);
        double avg = global.getMean();
        System.out.printf("Global metrics: %d entries\n", global.getTotalCount());
        System.out.printf("min/avg/max = %d/%f/%d\n", global.getMinValue(), avg, global.getMaxValue());

        if (percentiles) showPercentiles("Global percentiles", global);
        if (highest > 0) showHighest(tree, highest);

        return 0;
    }

    private Histogram showRootMetrics(Collection<Span> spans) {
        Map<String, List<Span>> byOperations = spans.stream()
              .collect(Collectors.groupingBy(Span::operation));

        Histogram histogram = null;
        for (Map.Entry<String, List<Span>> entry : byOperations.entrySet()) {
            System.out.printf("\toperation `%s` has %d entries\n", entry.getKey(), entry.getValue().size());

            Histogram h = showOperationMetrics(entry.getKey(), entry.getValue());
            if (histogram == null) {
                histogram = h;
            } else {
                histogram.add(h);
            }
        }

        return Objects.requireNonNull(histogram, "Histogram should not be null");
    }

    private Histogram showOperationMetrics(String operation, List<Span> spans) {
        Histogram histogram = spans.stream()
              .reduce(new Histogram(TimeUnit.MINUTES.toNanos(1), 0), (acc, curr) -> {
                  acc.recordValue(curr.duration.toNanos());
                  return acc;
              }, JfrParser::combineHistograms);

        double avg = histogram.getMean();
        System.out.printf("\t\t`%s` -> min/avg/max = %d/%f/%d\n", operation, histogram.getMinValue(), avg, histogram.getMaxValue());

        if (percentiles) showPercentiles(String.format("---- Percentiles `%s` ----", operation), histogram);

        return histogram;
    }

    private static Histogram combineHistograms(Histogram h1, Histogram h2) {
        h1.add(h2);
        return h1;
    }

    private static void showPercentiles(String message, Histogram histogram) {
        System.out.println(message);
        for (HistogramIterationValue hiv : histogram.percentiles(1)) {
            System.out.printf("%fP: %d ms (%d entries)\n", hiv.getPercentile(), hiv.getValueIteratedTo(), hiv.getCountAtValueIteratedTo());
        }
        System.out.println(" ---- ");
    }

    private static void showHighest(Tree tree, int highest) {
        System.out.printf("\n ----- Highest %d requests -----\n", highest);
        tree.roots.stream()
              .sorted((a1, a2) -> Long.compare(a2.duration.toNanos(), a1.duration.toNanos()))
              .limit(highest)
              .forEach(tree::showCompleteExecution);
    }

    private Stream<Span> read() {
        return Arrays.stream(files)
              .map(Path::of)
              .map(JfrParser::uncheckedReadAllEvents)
              .flatMap(Collection::stream)
              .filter(this::acceptEvent)
              .map(Span::from)
              .filter(s -> s.isAfter(after))
              .filter(s -> s.isBefore(before));
    }

    private boolean acceptEvent(RecordedEvent event) {
        return event.getEventType().getCategoryNames().contains(category);
    }

    private static List<RecordedEvent> uncheckedReadAllEvents(Path path) {
       try {
          return RecordingFile.readAllEvents(path);
       } catch (IOException e) {
          throw new RuntimeException(e);
       }
    }

    private Tree createTree(List<Span> spans) {
        Map<String, Span> index = new HashMap<>();
        Set<Span> roots = new HashSet<>();
        for (Span span : spans) {
            if (span.isRoot()) roots.add(span);

            index.put(span.trace, span);
        }

        return new Tree(index, roots);
    }

    private record Tree(Map<String, Span> index, Set<Span> roots) {

        private void showCompleteExecution(Span root) {
            assert roots.contains(root) : root + " is not a root element";
            StringBuilder sb = new StringBuilder();
            printTree(root, sb, 0);

            System.out.println(sb);
        }

        private void printTree(Span root, StringBuilder sb, int indentation) {
            print(root, sb, indentation);

            for (Span span : index.values()) {
                if (span.parent.equals(root.span)) {
                    printTree(span, sb, indentation + 2);
                }
            }
        }

        private void print(Span element, StringBuilder sb, int indentation) {
            if (indentation > 0) {
                sb.append(" ".repeat(indentation));
            }
            sb.append(element.toPrettyString())
                  .append(System.lineSeparator());
        }
    }

    private record Span(ZonedDateTime start, Duration duration, String operation, String trace, String span, String parent) {
        public static Span from(RecordedEvent event) {
            ZonedDateTime start = event.getStartTime().atZone(ZoneId.systemDefault());
            Duration duration = event.getDuration();
            String operation = null;
            String trace = null;
            String span = null;
            String parent = null;

            for (ValueDescriptor v : event.getFields()) {
                switch (v.getName()) {
                    case "operation" -> operation = event.getValue(v.getName());
                    case "trace" -> trace = event.getValue(v.getName());
                    case "span" -> span = event.getValue(v.getName());
                    case "parent" -> parent = event.getValue [...]

2024-07-03 16:42 UTC, pruivo commented
I would add the `JfrParser` into the `infinispan-tools` modules. Seems something nice to have :+1:

2024-07-03 16:53 UTC, pruivo commented
> This is to get an idea while running the benchmarks. Some information is still left out, like the category, node name, etc. The `Event` class of JFR accepts pretty much only primitives.

Did you check `SpanData.getAttributes()`? That information is set as attributes as we may find it there :crossed_fingers: 
https://github.com/infinispan/infinispan/blob/63c1eca6a94e5d6a478591a8543e86646a00b0ba/server/core/src/main/java/org/infinispan/server/core/telemetry/OpenTelemetryService.java#L67-L72

2024-07-03 22:43 UTC, infinispanrelease commented
Image pushed for Jenkins build [#2](https://ci.infinispan.org/job/Infinispan/job/PR-12599/2/):
```
quay.io/infinispan-test/server:PR-12599
```

2024-07-05 11:22 UTC, jabolina commented
> Did you check `SpanData.getAttributes()`? That information is set as attributes as we may find it there 🤞

I retrieved the attributes from there. Not the nicest API, though.


I'll open a JIRA and update this PR so we can have this ready.

2024-07-05 18:01 UTC, pruivo requested changes
I have some minor suggestions :)

2024-07-05 20:59 UTC, jabolina commented on core/src/main/java/org/infinispan/configuration/global/GlobalTracingConfiguration.java
> +      if (collectorEndpoint() != null) return true;
Correct. Otherwise, it would need to set a value for the endpoint. Looking now, I need to change to also check the enabled.

2024-07-05 21:09 UTC, jabolina commented on server/core/src/main/java/org/infinispan/server/core/telemetry/jfr/JfrSpanProcessor.java
> +      return CompletableResultCode.ofSuccess();
Wondering if it should be a weak map?

2024-09-09 09:26 UTC, pruivo approved these changes

2024-09-09 09:28 UTC, pruivo commented
@ fax4ever would you like to look at this PR since it is related to tracing?

2024-09-09 12:04 UTC, fax4ever commented
> @ fax4ever would you like to look at this PR since it is related to tracing?

I trust you. +1 to merge from me

2024-09-09 13:41 UTC, merged

2024-09-09 13:41 UTC, pruivo commented
merged! thanks @jabolina @fax4ever :+1: