Resp EVAL/EVAL_RO/EVALSHA/EVALSHA_RO/SCRIPT LOAD|EXISTS|FLUSH
infinispan/infinispan pull request #13203
Opened 2024-11-22 13:16 UTC by tristantarrant

Depends on #13190 

I will also add a section on scripting to the resp docs once #13198 is merged

Closes #13192

2024-11-22 15:26 UTC, tristantarrant commented
I need to exclude the lua stuff from the native server

2024-11-22 20:48 UTC, Saulzi commented
Does this add support for these resp commands?

I am looking at the feasibility of using infinispan as a drop in replacement for the Redis, unfortunately it will not work with the .NET client for redis (StackExchange.Redis) as Infinispan does not support the eval command, I am not sure which other commands may be required,

It does not look like the HotRod client for .NET has been updated in some time, 

Really what I am looking to do is use the Infinispan as a distributed cache in .NET (IDistributedCache) but I cannot find any recent / supported libraries to do this,

2024-11-23 07:24 UTC, tristantarrant commented
Yes, this adds those commands. I will use that client as additional validation that it  works and I'll update you.

2025-02-05 14:15 UTC, rigazilla commented on server/resp/src/main/java/org/infinispan/server/resp/RespRequestHandler.java
> +      assert writer.isInternal() || ctx.channel().eventLoop().inEventLoop() : "Buffer allocation should occur in event loop, it was " + Thread.currentThread().getName();
I have test errors for writer==null

2025-02-05 15:10 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/RespRequestHandler.java
> +      assert writer.isInternal() || ctx.channel().eventLoop().inEventLoop() : "Buffer allocation should occur in event loop, it was " + Thread.currentThread().getName();
Fixed

2025-02-05 15:35 UTC, jabolina reviewed
Looking great, just a few things.

2025-02-05 15:35 UTC, jabolina commented on server/resp/src/main/java/org/infinispan/server/resp/scripting/LuaTaskEngine.java
> +               handler.writer().string(ok);
These characters should be fine with the `string` method. It could be problematic for a simple string.

2025-02-05 15:35 UTC, jabolina commented on server/resp/src/main/java/org/infinispan/server/resp/serialization/lua/LuaResponseWriter.java
> +   public void simpleString(CharSequence value) {
I guess these string, integer, and double methods needs to check for null.

2025-02-05 15:35 UTC, jabolina commented on server/resp/src/main/java/org/infinispan/server/resp/serialization/lua/LuaResponseWriter.java
> +      throw new UnsupportedOperationException(CallerId.getCallerMethodName(1));
Should it be no-op? I see the method is called directly by some commands in the sorted set.

2025-02-05 15:35 UTC, jabolina commented on server/resp/src/main/java/org/infinispan/server/resp/commands/scripting/eval/EVAL.java
> +      super(-3, 1, 1, 1);
Seems it should be `-3, 0, 0, 0`:

```text
350)  1) "eval"
      2) (integer) -3
      3) 1) noscript
         2) stale
         3) skip_monitor
         4) no_mandatory_keys
         5) movablekeys
      4) (integer) 0
      5) (integer) 0
      6) (integer) 0

```

2025-02-05 15:35 UTC, jabolina commented on server/resp/src/main/java/org/infinispan/server/resp/commands/scripting/eval/FLUSH.java
> +      super(2, 0, 0, 0);
It should be -2.

2025-02-05 15:35 UTC, jabolina commented on server/resp/src/main/java/org/infinispan/server/resp/commands/scripting/eval/KILL.java
> +      super(-3, 0, 0, 0);
This one is 2 instead.

2025-02-05 16:49 UTC, rigazilla requested changes

2025-02-05 16:49 UTC, rigazilla commented on server/resp/src/main/java/org/infinispan/server/resp/scripting/LuaArray.java
> +         return null;
always returns null, is it ok?

2025-02-05 16:49 UTC, rigazilla commented on server/resp/src/main/java/org/infinispan/server/resp/commands/scripting/eval/DEBUG.java
> + * @since 15.1
```suggestion
 * @since 15.2
```

2025-02-05 16:49 UTC, rigazilla commented on server/resp/src/main/java/org/infinispan/server/resp/commands/scripting/eval/EVAL.java
> +      for (int i = 0; i < numKeys; i++) {
should we check the number of args?
```
127.0.0.1:6379> eval "return 0" 3 a
(error) ERR Number of keys can't be greater than number of args
```

2025-02-05 21:17 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/RespServer.java
> +      return random;
If we want to mirror the original behaviour, where there is only one thread, there should only be a single instance.

2025-02-05 21:17 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/scripting/LuaContext.java
> +         handler.respServer().random().setSeed(l.toInteger(1));
Yes, the seed is shared.

2025-02-06 10:48 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/scripting/LuaContextPool.java
> +      }, validationInterval, validationInterval, TimeUnit.SECONDS);
I've removed the executor completely now.

2025-02-06 10:48 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/scripting/LuaContext.java
> +         // As Infinispan doesn't handle RESP 2, should we throw an error here ?
Ok, I've removed the comment

2025-02-06 10:49 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/scripting/LuaContext.java
> +         Throwable cause = filterCause(t);
I've added a debug message

2025-02-06 10:49 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/scripting/LuaContext.java
> +      CompletableFuture<RespRequestHandler> future = ((Resp3Command) respCommand).perform(handler, ctx, args).toCompletableFuture();
I've applied the suggestion

2025-02-06 10:49 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/serialization/lua/LuaResponseWriter.java
> +   public void simpleString(CharSequence value) {
I've added null checks to all methods

2025-02-06 10:50 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/commands/scripting/eval/EVAL.java
> +      super(-3, 1, 1, 1);
Fixed

2025-02-06 10:50 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/commands/scripting/eval/FLUSH.java
> +      super(2, 0, 0, 0);
Fixed

2025-02-06 10:50 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/commands/scripting/eval/KILL.java
> +      super(-3, 0, 0, 0);
Fixed

2025-02-06 10:50 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/commands/scripting/eval/EVAL.java
> + * @since 15.1
Fixed

2025-02-06 10:50 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/scripting/LuaArray.java
> +         return null;
I've added a comment clarifying the way it work

2025-02-06 10:50 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/commands/scripting/eval/DEBUG.java
> + * @since 15.1
Fixed

2025-02-06 10:51 UTC, tristantarrant commented on build/configuration/pom.xml
> +      <version.fabric8.kubernetes-client>6.13.4</version.fabric8.kubernetes-client>
Done

2025-02-06 10:51 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java
> +            return possible;
Done

2025-02-12 18:49 UTC, tristantarrant commented
@jabolina @wburns I am not going to fix all the issues in this PR (custom serializers and RESP2). I'll just fix the current failures

2025-02-14 17:07 UTC, tristantarrant commented
I've fixed all the custom serializers, except some edge cases (`COMMAND` which cannot be invoked in a Lua script, and the `CLUSTER SLOTS|SHARDS`) and I've added the skeleton for handling RESP2 (although attempting to use it will throw an error).

2025-02-27 23:31 UTC, wburns requested changes

2025-02-27 23:31 UTC, wburns commented on server/resp/src/main/java/org/infinispan/server/resp/scripting/LuaTaskEngine.java
> +            luaCtx.unregisterScript(script);
Do we need to close the luaCtx if there was an exception? It won't be returned to the pool and the other stuff in `thenApplyAsync` won't run either.

2025-02-27 23:31 UTC, wburns commented on server/resp/src/main/java/org/infinispan/server/resp/scripting/LuaTaskEngine.java
> +            throw new RuntimeException("NOSCRIPT No matching script. Please use EVAL.");
Same here we need to make sure to handle the ctx better when exceptions occur.

2025-02-27 23:31 UTC, wburns commented on server/resp/src/main/java/org/infinispan/server/resp/scripting/LuaTaskEngine.java
> +         throw new RuntimeException(t);
This RuntimeException seems extraneous. I also worry that if an exception does happen, nothing is propagated to the user as the handler isn't written to.

2025-02-27 23:31 UTC, wburns commented on server/resp/src/main/java/org/infinispan/server/resp/serialization/bytebuf/ByteBufCollectionSerializer.java
> +         return object instanceof Collection<?>;
Is this change needed? I am a bit surprised at the change as this deals with the ByteBuf serializer..

2025-02-27 23:31 UTC, wburns commented on server/resp/src/main/java/org/infinispan/server/resp/serialization/lua/LuaResponseWriter.java
> +         lua.push(new String(value, StandardCharsets.US_ASCII));
I don't know if we can assume US_ASCII here. I believe this can contain any user value, so it can be any byte value.

2025-02-27 23:31 UTC, wburns commented on server/resp/src/main/java/org/infinispan/server/resp/serialization/lua/LuaResponseWriter.java
> +            lua.setTable(-3);
Have to admit all these magical numbers are not helpful. Maybe we should have these special values on an interface commenting what they mean?

2025-02-27 23:31 UTC, wburns commented on server/resp/src/main/java/org/infinispan/server/resp/serialization/lua/LuaResponseWriter.java
> +      throw new UnsupportedOperationException("emptySet"); // Only used by COMMAND which cannot be called from Lua.
Is it possible we add other commands that may support this though? I fear no one will update this and the command added won't be tested by a lua script we are testing. Maybe we should still implement or is it difficult to do so?

2025-02-27 23:31 UTC, wburns commented on server/resp/src/main/java/org/infinispan/server/resp/serialization/lua/LuaResponseWriter.java
> +      throw new UnsupportedOperationException(CallerId.getCallerMethodName(1));
Same here, I don't know if I like the idea of leaving these little time bombs that most likely will never seen unless someone in prod or a random dev/qe dog foods and finds it later.

2025-02-27 23:31 UTC, wburns commented on server/resp/src/main/java/org/infinispan/server/resp/serialization/lua/LuaResponseWriter.java
> +      throw new UnsupportedOperationException(CallerId.getCallerMethodName(1));
Shouldn't this work though if you use the provided serializer?

2025-02-27 23:31 UTC, wburns commented on server/resp/src/main/java/org/infinispan/server/resp/serialization/lua/LuaResponseWriter.java
> +      throw new UnsupportedOperationException(CallerId.getCallerMethodName(1));
Agreed, I don't feel comfortable with any of these methods throwing an exception tbh.

2025-02-27 23:31 UTC, wburns commented on server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java
> +   private static final long DISK_USAGE_UPPER_BOUND = 75_000_000L;
Is it okay changing the range from 5 MB to 2MB?

2025-03-06 07:12 UTC, tristantarrant commented on server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java
> +   private static final long DISK_USAGE_UPPER_BOUND = 75_000_000L;
Disk footprint changes very rarely, and, unfortunately, it decreases even more rarely :)

2025-03-06 07:17 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/RespVersion.java
> +public enum RespVersion {
The intention is that we also support RESP2 https://github.com/infinispan/infinispan/issues/13986

2025-03-06 07:17 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/commands/scripting/eval/DEBUG.java
> +      return handler.myStage();
I'm removint DEBUG and KILL, since we cannot implement them without https://github.com/gudzpoz/luajava/issues/227

2025-03-06 07:25 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java
> +      if (type instanceof Resp3Command resp3Command) {
`HELLO` is not.

2025-03-06 07:49 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/commands/scripting/eval/KILL.java
> +      return handler.myStage();
I'm removing this.

2025-03-06 07:53 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/commands/scripting/eval/EXISTS.java
> +               .supplyBlocking(() -> handler.respServer().luaEngine().scriptExists(shas), "script exists")
This is actually simpler to implement as is, and since this should be an infrequently invoked command, I'd rather keep it this way.

2025-03-06 08:53 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/scripting/LuaArray.java
> +      this(lua, index, lua.rawLength(index));
index is the position on the Lua stack.

2025-03-06 10:55 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/serialization/lua/LuaResponseWriter.java
> +            lua.setTable(-3);
nothing magical here: https://www.lua.org/manual/5.1/manual.html#lua_settable

2025-03-06 11:08 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/RespCommand.java
> +      byte[] buf = s.getBytes(StandardCharsets.US_ASCII);
I've changed this so that no allocation happens.

2025-03-06 11:08 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/scripting/ScriptFlags.java
> +   NO_WRITES(1),
I've added comments for all flags

2025-03-06 11:08 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/commands/scripting/eval/FLUSH.java
> +   private static final byte[] ASYNC_BYTES = "ASYNC".getBytes(StandardCharsets.US_ASCII);
I've removed them

2025-03-06 11:09 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/response/LCSResponse.java
> +         Map<byte[], Object> map = new LinkedHashMap<>(2);
I've explained the reason

2025-03-06 11:10 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/scripting/LuaContextPool.java
> +      pool = new ConcurrentLinkedQueue<>();
Done

2025-03-06 11:10 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/scripting/LuaMap.java
> +   static final Entry<Object, Object> EMPTY_ENTRY = Map.of(new Object(), new Object()).entrySet().iterator().next();
Done

2025-03-06 11:11 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/scripting/LuaTaskEngine.java
> +            luaCtx.unregisterScript(script);
I've reworked this

2025-03-06 11:11 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/scripting/LuaTaskEngine.java
> +            throw new RuntimeException("NOSCRIPT No matching script. Please use EVAL.");
I've reworked this

2025-03-06 11:12 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/scripting/LuaTaskEngine.java
> +         throw new RuntimeException(t);
With the change in the callers, this should be handled properly now

2025-03-06 11:12 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/serialization/lua/LuaResponseWriter.java
> +         lua.push(new String(value, StandardCharsets.US_ASCII));
I've changed it to use ISO8859-1 instead and added an explanation

2025-03-06 11:13 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/serialization/lua/LuaResponseWriter.java
> +      throw new UnsupportedOperationException(CallerId.getCallerMethodName(1));
The "hand-written" serializers won't work: the lua responses must adhere to well-known RESP structures.

2025-03-06 11:21 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/serialization/lua/LuaResponseWriter.java
> +      throw new UnsupportedOperationException(CallerId.getCallerMethodName(1));
I've rewritten most of the commands doing this to use proper RESP structures, instead of doing things by hand. The only significant leftover is `EXEC`. It looks like I should rewrite it to collect all responses into an array and write it at the end

2025-03-06 12:56 UTC, tristantarrant commented
@wburns (replying here because GitHub doesn't let me reply to your comment):

> Looking at LuaContext, I don't think this will work as all of the lua instances will share the same Random object

That's the intention. In Redis there is only one engine

2025-03-06 12:59 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/serialization/lua/LuaResponseWriter.java
> +      throw new UnsupportedOperationException("emptySet"); // Only used by COMMAND which cannot be called from Lua.
Probably, but that means creating tests just to exercise parts of the code that won't ever be executed at the moment

2025-03-07 12:48 UTC, tristantarrant commented
@wburns I should have addressed all issues

2025-03-07 23:09 UTC, wburns commented on server/resp/src/main/java/org/infinispan/server/resp/serialization/lua/LuaResponseWriter.java
> +            lua.setTable(-3);
It is magical in the sense that we have to look it up somewhere else that isn't in the code. I know it has a defined purpose.

2025-03-08 07:39 UTC, tristantarrant commented on server/resp/src/main/java/org/infinispan/server/resp/serialization/lua/LuaResponseWriter.java
> +            lua.setTable(-3);
I have sprinkled a bunch of comments which should make things clearer

2025-03-10 18:49 UTC, wburns commented on server/resp/src/main/java/org/infinispan/server/resp/serialization/lua/LuaResponseWriter.java
> +   public void arrayNext() {
Have to admit, I am not a fan of this method from the caller perspective as I feel we could know we are inside an array and do this. But it does make this class a lot less cluttered, so I will not push back on it.

2025-03-10 18:56 UTC, merged

2025-03-10 18:56 UTC, wburns commented
Integrated into main, thanks @tristantarrant !