[#13247] Replace GlobalMarshaller with protobuf based marshaller
infinispan/infinispan pull request #13316
Opened 2024-12-11 12:04 UTC by ryanemerson

Closes #13247

For 16.0.0-SNAPSHOT. Depends upon https://github.com/infinispan/infinispan/pull/13259

Apologies in advance for the large diff :scream:

I suggest that we approach the review of this PR by getting SMEs to review commands/classes associated with their areas. However, before that I think it would be prudent if a couple of volunteers reviewed the changes to the GlobalMarshaller and Protostream constructs to ensure that we're happy with the approach before all uses are reviewed.

I'm creating a draft PR to begin until CI is green, or close to it. Once CI is in a good shape, the reviewing can start in earnest :slightly_smiling_face: 

Docs will be handled in a separate PR.

# Marshallable* Wrappers

In the `org.infinispan.marshall.protostream.impl` package there are several different `Marshallable*` wrapper classes. It's necessary to use these so that we can delegate down to a user marshaller if one is configured. We can't just use a `WrappedMessage` as it's not aware of the user marshaller and so if a user configures jboss-marshalling or Java Serialization it has no way of marshalling the user classes. This is probably the trickiest part of this conversion.

In general I have tried to use `WrappedMessage` when polymorphism is required, but we *know* that a user provided value is never applicable. For all other use-cases I default to the `Marshallable*` wrappers. My branche(s) have been worked on over multiple years as this feature has come in and out of fashion, so it's possible that there are inconsistencies, please comment if you think you find one!

The `MarshallableWrappers*` work from a functional perspective, but I'm sure we can make them more efficient and potentially reduce the amount of wrapping required here. Any ideas here are greatly appreciated!

# Performance

So far my efforts have been focused on functionality, not performance. The previous marshaller was very efficient in many ways, so we will have to evolve this solution to minimise the performance cost of the migration.

In order for the `core` tests to consistently pass on my local machine without an OOM i had to increase the default xmx to 1.5Gb.

## ProtoStream TypeIds
I have applied a TypeId to nearly all messages that we will be sending over the wire to reduce the payload. For the TypeIds we have a very small range where this TypeId can be a single byte instead of two. I have not tried experimenting with applying the single byte id to more frequently used messages yet, this is a perf optimisation we can make as we go, probably in a follow up PR.

## Caching Objects
The old GlobalMarshaller did many tricks to reuse objects. So far I have avoided this for simplicity, but we can/should look more into these aspects once we know what the performance cost is of the conversion in it's current form.

2024-12-17 10:37 UTC, pruivo commented
Do you plan to to open a smaller PR into the feature branch to remove the deprecated commands as
```
   @Deprecated(since = "15.1", forRemoval = true)
   default XSiteBringOnlineCommand buildXSiteBringOnlineCommand(String siteName) {
      return null;
   }

   @Deprecated(since = "15.1", forRemoval = true)
   default XSiteOfflineStatusCommand buildXSiteOfflineStatusCommand(String siteName)  {
      return null;
   }

   @Deprecated(since = "15.1", forRemoval = true)
   default XSiteStatusCommand buildXSiteStatusCommand() {
      return null;
   }

   @Deprecated(since = "15.1", forRemoval = true)
   default XSiteTakeOfflineCommand buildXSiteTakeOfflineCommand(String siteName) {
      return null;
   }
```
I've noticed some enum values being deprecated too. 
Some commits in this PR may be in a separated PR to make this smaller and motivate us to review it :rofl:

2024-12-17 11:01 UTC, ryanemerson commented
> Do you plan to to open a smaller PR into the feature branch to remove the deprecated commands as

That's a good idea! My focus has been on getting things functional, but I'm getting tired of debugging tests, so I'll do that now :slightly_smiling_face:

2025-01-03 11:26 UTC, pruivo commented on client/hotrod-client-legacy/src/test/java/org/infinispan/client/hotrod/event/ContinuousQueryObjectStorageTest.java
> +      return Arrays.asList(GlobalContextInitializer.INSTANCE, TestDomainSCI.INSTANCE, ClientEventSCI.INSTANCE);
I've noticed `GlobalContextInitializer.INSTANCE` is added in most of the tests. Would it make sense if the cache manager automatically adds it?

2025-01-03 11:26 UTC, pruivo commented on client/hotrod-client-legacy/src/test/java/org/infinispan/client/hotrod/test/MultiHotRodServersTest.java
> +            .socketTimeout(Integer.MAX_VALUE)
any problem with the server? If the legacy client is going to be removed in ISPN16, it is probably worth to open a PR and remove it.

2025-01-03 11:26 UTC, pruivo commented on commons/all/src/main/java/org/infinispan/commons/api/CacheContainerAdmin.java
>     enum AdminFlag {
It can be annotated with `@Proto` and remove `@ProtoEnumValue`. It looks cleaner to me. Just my 2 cents.

2025-01-03 11:26 UTC, pruivo commented on commons/all/src/main/java/org/infinispan/commons/api/CacheContainerAdmin.java
>        @Deprecated(forRemoval=true, since = "11.0")
Remove the deprecated value in this PR or a separated PR.

2025-01-07 14:25 UTC, ryanemerson commented on commons/all/src/main/java/org/infinispan/commons/api/CacheContainerAdmin.java
>        @Deprecated(forRemoval=true, since = "11.0")
I've created a separate PR for the feature branch: https://github.com/infinispan/infinispan/pull/13651

2025-01-07 14:31 UTC, ryanemerson commented on commons/all/src/main/java/org/infinispan/commons/api/CacheContainerAdmin.java
>     enum AdminFlag {
I'll update. I suspect there will be a few more instances where this is the case, the joys of converting some of the code a long time ago before `@Proto` was available.

2025-01-07 14:31 UTC, ryanemerson commented on client/hotrod-client-legacy/src/test/java/org/infinispan/client/hotrod/test/MultiHotRodServersTest.java
> +            .socketTimeout(Integer.MAX_VALUE)
I think this is just a left over from when I was debugging a test. I'll revert

2025-01-21 13:46 UTC, pruivo commented on core/src/main/java/org/infinispan/marshall/protostream/impl/MarshallableArray.java
> +public class MarshallableArray<T> {
Why do we need this class? 
Isn't protostream using this class to handle arrays of objects?
https://github.com/infinispan/protostream/blob/main/types/src/main/java/org/infinispan/protostream/types/java/arrays/ObjectArrayAdapter.java

2025-01-21 14:21 UTC, pruivo commented on core/src/main/java/org/infinispan/marshall/protostream/impl/MarshallableArray.java
> +public class MarshallableArray<T> {
I forgot that small detail that users can configure a different marshaller :cry: 
Follow-up question, can the `collection` be removed? it is unnecessary if you send the array length.

2025-01-21 16:57 UTC, ryanemerson commented on core/src/main/java/org/infinispan/marshall/protostream/impl/MarshallableArray.java
> +public class MarshallableArray<T> {
The idea of having both the `collection` and `array` field was to prevent a call to `toArray` unnecessarily. We could write the array length like you say, but then we're adding field ordering logic to the parser which we're technically not supposed to do:

https://protobuf.dev/programming-guides/encoding/#order
```quote
When a message is serialized, there is no guaranteed order for how its known or [unknown fields](https://protobuf.dev/programming-guides/proto2#updating) will be written. Serialization order is an implementation detail, and the details of any particular implementation may change in the future. Therefore, protocol buffer parsers must be able to parse fields in any order.
``` 

Given that this is a very niche use-case, we could make an exception, WDYT?

2025-01-21 17:57 UTC, pruivo commented on core/src/main/java/org/infinispan/marshall/protostream/impl/MarshallableArray.java
> +public class MarshallableArray<T> {
Taking into consideration that we use `Arrays.hashCode` and `Arrays.equals` when fetching keys, the field order must be kept otherwise we are in big trouble.

2025-01-21 18:25 UTC, jabolina reviewed
Just a question on the RESP module.

2025-01-21 21:14 UTC, wburns commented
It appears the memory usage is because of Mockito invocations being stored for some reason... still looking.

2025-01-22 09:06 UTC, fax4ever approved these changes
From the query area, everything looks good to me.
Thank you @ryanemerson for this very critical and extensive work.

Just one general question, I noticed that the protobuf schemas for our internal entities are not visible, for instance from the web console. This is good.
So the user cannot change them, for instance overriding the schema name / files. Correct? Thanks

2025-01-22 09:16 UTC, ryanemerson commented
> So the user cannot change them, for instance overriding the schema name / files. Correct? Thanks

Exactly! The internal proto schemas should be of no concern to users as it's purely an internal concern. If the proto schemas somehow iverged from their generated marshallers, there would be all kind of problems.

2025-01-22 23:42 UTC, wburns commented
It seems with the new change if I have the server in my build class path that I must also have the query module in my runtime path. Why the disconnect? If it isn't in the build path, why does it have to be in the runtime one? It is also required if I even use an embedded cache without the server, if I have the server in the class path. Just seems very inconsistent to me.

You get `Caused by: java.lang.NoClassDefFoundError: org/infinispan/query/remote/impl/persistence/PersistenceContextInitializerImpl` if query is not in the runtime path.

2025-01-23 10:32 UTC, ryanemerson commented
@wburns That was caused because I had added a dependency on `org.infinispan.query.remote.impl.persistence.PersistenceContextInitializer.class` in the server/hotrod `GlobalContextInitializer`, but I can't remember why I did that. Removing this fixes the build and removes the need for the additional dependency. Let's see what CI thinks :crossed_fingers:

2025-01-23 10:42 UTC, ryanemerson commented on server/resp/src/main/java/org/infinispan/server/resp/commands/tx/WATCH.java
> +@ProtoTypeId(ProtoStreamTypeIds.RESP_WATCH)
Good catch! I'm not sure why I thought this was necessary, I removed it and the module tests all pass :tada:

2025-01-24 16:32 UTC, pruivo commented
The clustered-counter module looks fine to me. The only nitpicking is the `default="-1"` as I think it makes more sense to default to zero. 

Maybe we should add a list in the first post with the modules verified. WDYT @ryanemerson ?

2025-01-27 11:33 UTC, pruivo reviewed
pushing more comments before the browser crashes...

2025-01-27 11:33 UTC, pruivo commented on core/src/main/java/org/infinispan/remoting/responses/PrepareResponse.java
>  public class PrepareResponse extends ValidResponse {
No reason to extend `ValidResponse`.

2025-01-27 11:33 UTC, pruivo commented on core/src/main/java/org/infinispan/remoting/responses/PrepareResponse.java
> +   MarshallableMap<Integer, IracMetadata> getNewIracMetadata() {
Both `Integer` and `IracMetadata` are supported proto3 Map entities. Wrapping is not required.

2025-01-27 11:33 UTC, pruivo commented on core/src/main/java/org/infinispan/remoting/responses/SuccessfulResponse.java
>  public class SuccessfulResponse<T> extends ValidResponse {
Since it is in the critical path of all operations, I would convert this to an interface and have different implementation for each response value:

* empty/null
* object
* array
* bytes
* collection
* map

2025-01-27 11:33 UTC, pruivo commented on core/src/main/java/org/infinispan/remoting/responses/SuccessfulResponse.java
>  public class SuccessfulResponse<T> extends ValidResponse {
Same idea for UnsuccessfulResponse.

2025-01-27 11:33 UTC, pruivo commented on core/src/main/java/org/infinispan/remoting/responses/BiasRevocationResponse.java
>  public class BiasRevocationResponse extends SuccessfulResponse {
No usage found in the IDE. Can be removed.

2025-01-27 11:53 UTC, ryanemerson commented on core/src/main/java/org/infinispan/remoting/responses/BiasRevocationResponse.java
>  public class BiasRevocationResponse extends SuccessfulResponse {
I've created a PR for `main`: https://github.com/infinispan/infinispan/pull/13877

2025-01-27 19:07 UTC, ryanemerson commented on core/src/main/java/org/infinispan/remoting/responses/SuccessfulResponse.java
>  public class SuccessfulResponse<T> extends ValidResponse {
Good idea. This actually allows me to revert some of my earlier changes to the interceptor. I've pushed a commit with the change.

2025-01-27 21:36 UTC, jabolina reviewed
I started my way through core. Just flushing some comments before continuing.

2025-01-28 09:57 UTC, ryanemerson commented on core/src/main/java/org/infinispan/cache/impl/BiFunctionMapper.java
>     }
I think it is, but I'll just revert adding the generics as the calling code ignores them anyway.

2025-01-28 09:57 UTC, ryanemerson commented on core/src/main/java/org/infinispan/cache/impl/FunctionMapper.java
> +      T key = (T) keyDataConversion.fromStorage(k);
Reverted.

2025-01-28 10:03 UTC, ryanemerson commented on core/src/main/java/org/infinispan/commands/control/LockControlCommand.java
> +   @ProtoField(number = 4, name = "keys")
Good question! The good news is that if we add a new field to a base class and it's number is already used by a child class, compilation will fail, so we can never accidentally merge such a change.

Possible solutions:
1. We could allocate a range for the base class and then start from after that in child subclasses. I think this is potentially confusing and overkill given how stable a lot of these commands are. 
2. Add the next available field number with respect to all child class field numbers. The downside is that subsequent fields added to child classes will appear out of sequence with respect to other fields in their class. A comment in the child class would make the reason for this clear.

My preference is 2.

2025-01-28 10:10 UTC, ryanemerson commented on core/src/main/java/org/infinispan/commands/read/GetCacheEntryCommand.java
> -   public GetCacheEntryCommand() {
I don't think the command is replicated since [ISPN-9615](https://github.com/infinispan/infinispan/commit/342faf0eac96d21bfe8b062e0029c6cff05030c3) \cc @wburns . Maybe I should make it implement the `LocalCommand` interface?

2025-01-28 10:11 UTC, ryanemerson commented on core/src/main/java/org/infinispan/commands/write/ComputeCommand.java
> +   }
Exactly. Protobuf/Protostream do not handle polymorphism directly. Similarly, we have to use a `MarshallableObject` vs a `WrappedMessage` as it's possible for users to provide their own `Metadata` implementation and they might configure a custom user marshaller.

2025-01-28 10:31 UTC, ryanemerson commented on core/src/main/java/org/infinispan/commands/read/GetAllCommand.java
> +public class GetAllCommand extends AbstractTopologyAffectedCommand implements LocalCommand {
I'm not sure why the `LocalCommand` interface was not there previously, but as the command seemingly isn't required over the wirte, I think it makes sense to add it.

2025-01-28 22:33 UTC, wburns commented on core/src/main/java/org/infinispan/commands/read/GetCacheEntryCommand.java
> -   public GetCacheEntryCommand() {
It can be replicated as far as I know. https://github.com/infinispan/infinispan/blob/main/core/src/main/java/org/infinispan/interceptors/distribution/BaseDistributionInterceptor.java#L627

2025-02-14 11:52 UTC, pruivo requested changes

2025-02-14 11:52 UTC, pruivo commented on commons/all/src/main/java/org/infinispan/commons/util/ConcurrentSmallIntSet.java
> +
How do you feel about running more JMH performance tests? 
Using the new Protostream feature, `IntStream.range(0, array.length()).map(array::get);` may be better (or worse) 
Another alternative is to create an `Iterable` to iterate over `array` elements.

2025-02-14 11:52 UTC, pruivo commented on commons/all/src/main/java/org/infinispan/commons/hash/CRC16.java
> +@ProtoTypeId(ProtoStreamTypeIds.HASH_CRC16)
It is not present in the schema and I'm guessing it is not sent over the wire. There is no proto factory either.

2025-02-14 11:52 UTC, pruivo commented on commons/all/src/main/java/org/infinispan/commons/util/EmptyIntSet.java
> +   @ProtoFactory
can't use `getInstance()`?

2025-02-14 11:52 UTC, pruivo commented on core/src/main/java/org/infinispan/commands/AbstractTopologyAffectedCommand.java
> +   @ProtoField(number = 2, defaultValue = "-1")
why setting the default value to -1 in numeric fields and not use the java/protostream default of zero? 
The question is not related to this particular field, but I've seen this almost everywhere.

2025-02-14 11:52 UTC, pruivo commented on core/src/main/java/org/infinispan/commands/ReplicableCommand.java
>     byte getCommandId();
yes, I would deprecate it and add a default implementation returning zero. 
We need to fix our code where we rely on this, but in a follow up PR.

2025-02-14 12:18 UTC, ryanemerson commented on commons/all/src/main/java/org/infinispan/commons/util/ConcurrentSmallIntSet.java
> +
I think `Iterable` makes the most sense here, as we can then pass a `List` to the `@ProtoFactory` annotation so that we know the total number of elements and can size the `ConcurrentSmallIntSet` accordingly

2025-02-14 13:21 UTC, ryanemerson commented on commons/all/src/main/java/org/infinispan/commons/util/EmptyIntSet.java
> +   @ProtoFactory
:+1: If we change the return type to be the concrete implementation we can.

2025-02-14 13:28 UTC, ryanemerson commented on core/src/main/java/org/infinispan/commands/AbstractTopologyAffectedCommand.java
> +   @ProtoField(number = 2, defaultValue = "-1")
Good question. When I originally started working on this we only had PROTO2, so the defaultValue was always required. I *think* the reason I went with -1 was to aid with debugging, but I really can't be sure. I'll remove  the `defaultValue` definitions where a 0 value makes sense.

2025-02-14 14:08 UTC, pruivo commented on core/src/main/java/org/infinispan/commands/irac/IracRequestStateCommand.java
>     private IntSet segments;
maybe worth to change this to `SmallIntSet` to avoid wrapping?

2025-02-14 14:08 UTC, pruivo commented on core/src/main/java/org/infinispan/commands/irac/IracUpdateVersionCommand.java
> +   MarshallableMap<Integer, IracEntryVersion> getWrappedSegmentVersions() {
are using proto3? Wrapping shouldn't be required.

2025-02-14 16:01 UTC, pruivo commented on core/src/main/java/org/infinispan/filter/CompositeKeyValueFilter.java
>        this.filters = filters;
wouldn't be simpler to have a `MarshallableCollection` as a field?

2025-02-17 10:00 UTC, ryanemerson commented on core/src/main/java/org/infinispan/commands/AbstractTopologyAffectedCommand.java
> +   @ProtoField(number = 2, defaultValue = "-1")
I have added a commit that removes all redundant `defaultValue` and `number/value = ` from `@ProtoField` definitions. I have deliberately only applied the change to `@ProtoField` adapters updated as part of this PR as I didn't want to increase the diff further. If we want to modify any existing definitions, I think it should happen in a subsequent PR.

https://github.com/infinispan/infinispan/pull/13316/commits/a62e5794cadf325ac0ca1aeb43fac9dbf573e590

2025-02-17 10:07 UTC, ryanemerson commented on core/src/main/java/org/infinispan/commands/control/LockControlCommand.java
> +   private long flags;
It's redundant as we always pass the `long flags` arg via all constructors now.

2025-02-17 10:10 UTC, ryanemerson commented on core/src/main/java/org/infinispan/commands/control/LockControlCommand.java
> +      this.keys = keys == null ? Collections.emptyList() : new ArrayList<>(keys);
If we do this, don't we need to then wrap the `keys` in the `@ProtoFactory` so that an unmodifiable set is used?

2025-02-17 10:14 UTC, ryanemerson commented on core/src/main/java/org/infinispan/commands/irac/IracCleanupKeysCommand.java
> +   MarshallableCollection<IracManagerKeyInfo> getCleanup() {
Good spot, I obviously forgot to update this after my own PR to allow it :see_no_evil: 

https://github.com/infinispan/infinispan/pull/11546

2025-02-17 10:24 UTC, pruivo commented on core/src/main/java/org/infinispan/commands/control/LockControlCommand.java
> +      this.keys = keys == null ? Collections.emptyList() : new ArrayList<>(keys);
I think we are safe as the defensive copy is because the collection comes from user code:
https://github.com/infinispan/infinispan/blob/3c2aaa1cc192f6a68e05a355a214f22b63a50f34/core/src/main/java/org/infinispan/cache/impl/CacheImpl.java#L1016-L1029

Doing the defensive copy in the `CacheImpl` is probably better so we don't have to worry internally. It can be a different PR to main if you want to keep these unrelated changes outside this PR. WDYT?

2025-02-17 10:31 UTC, ryanemerson commented on core/src/main/java/org/infinispan/commands/irac/IracRequestStateCommand.java
>     private IntSet segments;
Can we guarantee that a `SmallIntSet` is always applicable? The `CommandsFactory` method signature is `IracRequestStateCommand buildIracRequestStateCommand(IntSet segments) `

2025-02-17 10:45 UTC, ryanemerson commented on core/src/main/java/org/infinispan/commands/irac/IracMetadataRequestCommand.java
> +public class IracMetadataRequestCommand extends BaseRpcCommand implements TopologyAffectedCommand {
I have introduced `BaseIracComman` that implements `CacheRpcCommand` directly.

2025-02-17 11:09 UTC, ryanemerson commented on core/src/main/java/org/infinispan/filter/CompositeKeyValueFilter.java
>        this.filters = filters;
Probably. This class is never used internally. Is there any reason to keep it around @wburns or can we deprecate in 15.2 and remove in 16.0?

2025-02-17 11:14 UTC, ryanemerson commented on core/src/main/java/org/infinispan/commands/control/LockControlCommand.java
> +      this.keys = keys == null ? Collections.emptyList() : new ArrayList<>(keys);
A separate PR sounds good. Lets isolate changes as much as possible.

2025-02-17 11:48 UTC, pruivo commented on core/src/main/java/org/infinispan/commands/irac/IracRequestStateCommand.java
>     private IntSet segments;
yes, I tracked it down here https://github.com/infinispan/infinispan/blob/e9d227d6df1e9a1a5034737dbab2c37b2c82a7d1/core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java#L216

This is only for state transfer, so probably not worth changing the entire methods chain.

2025-02-17 12:18 UTC, ryanemerson commented on core/src/main/java/org/infinispan/commands/tx/CommitCommand.java
> +   MarshallableMap<Integer, IracMetadata> getIracMetadataMap() {
Unfortunately I can't change this command until https://github.com/infinispan/protostream/issues/418 is fixed. Working on it now...

2025-02-17 12:25 UTC, ryanemerson commented on core/src/main/java/org/infinispan/commands/read/GetKeyValueCommand.java
> +@ProtoTypeId(ProtoStreamTypeIds.GET_KEY_VALUE_COMMAND)
It seems so. I have removed the Protostream annotations and have updated it to implement the `LocalCommand` interface.

2025-02-17 19:03 UTC, pruivo commented on core/src/main/java/org/infinispan/marshall/protostream/impl/MarshallableArray.java
> +                     writer.writeBytes(2, Util.EMPTY_BYTE_ARRAY);
similar to other comment about real empty byte arrays and null.

2025-02-17 19:04 UTC, pruivo commented on core/src/main/java/org/infinispan/marshall/protostream/impl/MarshallableArray.java
> +            List<Object> entries = new ArrayList<>(size);
why not `Object[] entries = new Object[size];`? You need to cast to `T[]` but avoid any copying.

2025-02-17 19:07 UTC, pruivo commented on core/src/main/java/org/infinispan/marshall/protostream/impl/MarshallableDeque.java
> +            queue instanceof Deque<T> deque ?
are we using Deque?

2025-02-18 09:49 UTC, ryanemerson commented on core/src/main/java/org/infinispan/marshall/protostream/impl/MarshallableDeque.java
> +            queue instanceof Deque<T> deque ?
We actually only need a `Queue` implementation for `CacheStreamIntermediateReducer`, but I implemented it as `Deque` to give us more flexibility in the future if needed.

2025-02-18 10:04 UTC, pruivo commented on core/src/main/java/org/infinispan/marshall/protostream/impl/AbstractInternalProtoStreamMarshaller.java
> +         return null;
In the main branch, the `GlobalMarshaller` handles the null and the ProtoStream (or any user configured marshaller) would never receive a null object

https://github.com/infinispan/infinispan/blob/4b085c4010af02f6df95a37a71afe7d0cfe672ed/core/src/main/java/org/infinispan/marshall/core/GlobalMarshaller.java#L347-L352

I think we don't have that protection in place and may be the reason we have so many conditions in the code like this. 
```
// If entry is null, write an empty byte array so that the null value can be recreated on the receiver.
    if (entry == null) {
       writer.writeBytes(2, Util.EMPTY_BYTE_ARRAY);
```

2025-02-18 10:15 UTC, ryanemerson commented on core/src/main/java/org/infinispan/marshall/protostream/impl/AbstractMarshallableCollection.java
> +                     writer.writeBytes(2, Util.EMPTY_BYTE_ARRAY);
Good point! I think calling `writer.writeBytes` with the result of the marshaller call will be sufficient as then the protobuf encoding will ensure that 0 bytes are represented and we can interpret that as null on the reader side.

2025-02-18 10:16 UTC, pruivo commented on core/src/main/java/org/infinispan/marshall/protostream/impl/MarshallableDeque.java
> +            queue instanceof Deque<T> deque ?
@wburns why is it a `Queue`? Can't it be a `List` as it seems only to invoke `add`?

2025-02-18 10:16 UTC, ryanemerson commented on core/src/main/java/org/infinispan/marshall/protostream/impl/AbstractInternalProtoStreamMarshaller.java
> +         return null;
Actually, I understand your point about `null` now that we need to modify the `MarshallableArray/Collection` marshallers to handle empty bytes.

2025-02-18 10:41 UTC, ryanemerson commented on core/src/main/java/org/infinispan/commands/remote/ClusteredGetCommand.java
> +   private final Integer segment;
I don't think we can do this in `main` as it will break compatibility between 15.2 and 15.1.x :disappointed:

I could issue such a PR against the feature branch?

2025-02-18 11:09 UTC, ryanemerson commented on core/src/main/java/org/infinispan/commands/topology/RebalancePhaseConfirmCommand.java
> +   final int viewId;
https://github.com/infinispan/infinispan/pull/14087

2025-02-18 15:45 UTC, wburns commented on core/src/main/java/org/infinispan/marshall/protostream/impl/MarshallableDeque.java
> +            queue instanceof Deque<T> deque ?
It can be, it was just Deque since it didn't need to have random access when I wrote this many years ago :) The code was changed to use Iterable anyways though afaik.

While I agree we can probably wait on supporting Queue, I don't think it hurts either.

2025-02-18 15:48 UTC, wburns commented on core/src/main/java/org/infinispan/filter/CompositeKeyValueFilter.java
>        this.filters = filters;
It was used at one point and is technically public. We could try deprecating if you want, but I doubt we will be able to remove it anytime soon and it shouldn't cause any maintenance head ache as it is pretty trivial.

2025-02-18 15:52 UTC, ryanemerson commented on core/src/main/java/org/infinispan/marshall/protostream/impl/MarshallableDeque.java
> +            queue instanceof Deque<T> deque ?
Unfortunately even with my Protostream enhancements we can't use `Iterable` directly in this case because we need to marshall an interface `IntermediateOperation`, not a concrete type.

Assuming `IntermediateOperation` implementations are always provided by us, we could do something like:

```java
   @ProtoField(number = 1)
   Stream<WrappedMessage> getIntermediateOperations() {
      return intOps.stream().map(WrappedMessage::new);
   }
```
The disadvantage being that we're creating a `WrappedMesssage` per op, which is avoided when using the various `Marshallable*` abstractions.

2025-02-18 18:55 UTC, pruivo commented on core/src/main/java/org/infinispan/reactive/publisher/impl/commands/batch/PublisherResponse.java
> +   MarshallableList<PublisherHandler.SegmentResult> getWrappedSegmentResults() {
no wrapping required.

2025-02-18 18:55 UTC, pruivo commented on core/src/main/java/org/infinispan/reactive/publisher/impl/commands/reduction/ReductionPublisherRequestCommand.java
> +   public int getTopologyId() {
This must be sent over the network too.

2025-02-18 18:55 UTC, pruivo commented on core/src/main/java/org/infinispan/topology/ManagerStatusResponse.java
> +   final MarshallableMap<String, CacheStatusResponse> caches;
remove wrapping?

2025-02-18 18:55 UTC, pruivo commented on core/src/main/java/org/infinispan/topology/PersistentUUID.java
> +   @ProtoField(1)
why not annotate `final UUID uuid`?

2025-02-18 18:55 UTC, pruivo commented on core/src/main/java/org/infinispan/xsite/commands/remote/XSiteStatePushRequest.java
> +   final XSiteState[] chunk;
if you feel that it is worth it, change to a List. Reading arrays is not very good with protostream; but state transfer should be rare.

2025-02-18 18:55 UTC, pruivo commented on core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStatePushCommand.java
> +   public XSiteState[] getChunk() {
same here

2025-02-18 18:55 UTC, pruivo commented on core/src/test/java/org/infinispan/distribution/DistSyncFuncTest.java
> +      System.out.println("-------------------------------------");
revert system.out here and below?

2025-02-18 18:55 UTC, pruivo commented on core/src/test/java/org/infinispan/lock/L1LockTest.java
> +      Object o = cache(1).get(localKey);
revert

2025-02-19 10:28 UTC, ryanemerson commented on core/src/main/java/org/infinispan/topology/PersistentUUID.java
> +   @ProtoField(1)
I'm guessing it's because I converted this class before we even had the UUIDAdapter :see_no_evil:

2025-02-19 10:32 UTC, ryanemerson commented on core/src/main/java/org/infinispan/reactive/publisher/impl/commands/reduction/ReductionPublisherRequestCommand.java
> +   public int getTopologyId() {
Good spot, I missed the `TopologyAffectedCommand` interface.

2025-02-19 11:09 UTC, ryanemerson commented on core/src/main/java/org/infinispan/xsite/commands/remote/XSiteStatePushRequest.java
> +   final XSiteState[] chunk;
I agree we should change it, but let's do it in a subsequent PR as it impacts a few interfaces. I have created https://github.com/infinispan/infinispan/issues/14109 and added it to this epic.

2025-02-19 14:15 UTC, ryanemerson commented on core/src/main/java/org/infinispan/commands/ReplicableCommand.java
>     byte getCommandId();
Issue created for a follow up PR: https://github.com/infinispan/infinispan/issues/14114

2025-02-19 14:41 UTC, ryanemerson commented on core/src/main/java/org/infinispan/commands/remote/ClusteredGetCommand.java
> +   private final Integer segment;
We discussed this on zulip and decided that null is a better fit for Protostream as it will use less bytes than having the segment as -1.

2025-02-19 14:56 UTC, ryanemerson commented on core/src/main/java/org/infinispan/filter/CompositeKeyValueFilter.java
>        this.filters = filters;
I've updated the class to use `MarshallableArray`. We can't use `MarshallableCollection` without copying as the constructor takes in varargs.

2025-02-20 11:24 UTC, ryanemerson commented on hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/util/EvictAllCommand.java
> +	final static ConcurrentMap<ByteString, InfinispanBaseRegion> allRegions = new ConcurrentHashMap<>();
I've created https://github.com/infinispan/infinispan/issues/14129, I'll issue a PR to `main`.

2025-02-20 17:12 UTC, merged

2025-02-20 17:12 UTC, wburns commented
Great work @ryanemerson !

2025-02-20 19:09 UTC, pruivo reviewed
Not sure if intentional, but the classes in `org.infinispan.stream.impl.intops.*` does not have an ID.

2025-02-20 19:09 UTC, pruivo commented on lock/src/main/java/org/infinispan/lock/impl/entries/ClusteredLockValue.java
> +   WrappedMessage getWrappedOwner() {
double check but the owner is always an `Address`/`JGroupsAddress`.

2025-02-20 19:09 UTC, pruivo commented on lock/src/main/java/org/infinispan/lock/impl/functions/IsLocked.java
> +   WrappedMessage getWrappedRequestor() {
here too.

2025-02-20 19:09 UTC, pruivo commented on lock/src/main/java/org/infinispan/lock/impl/functions/UnlockFunction.java
> +   Set<WrappedMessage> getRequesters() {
set of addresses :crossed_fingers:

2025-02-21 11:48 UTC, pruivo reviewed
A couple more changes to enums, the `CACHED_VALUES = values()` can be removed. I didn't comment on all the places. 

I think the `protostream-processor` can have the `provided` scope instead of being a runtime dependency and it isn't in all places.

2025-02-21 11:48 UTC, pruivo commented on server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/ClientAddress.java
> +   WrappedMessage getWrappedLocalAddress() {
99% sure it can be cast to JGroupsAddress.

2025-02-21 11:48 UTC, pruivo commented on server/resp/src/main/java/org/infinispan/server/resp/RespModuleLifecycle.java
> +      ctxRegistry.addContextInitializer(SerializationContextRegistry.MarshallerType.GLOBAL, new org.infinispan.server.resp.PersistenceContextInitializerImpl());
is it intentional adding `PersistenceContextInitializerImpl` to `MarshallerType.GLOBAL`?

2025-02-21 11:48 UTC, pruivo commented on server/resp/src/main/java/org/infinispan/server/resp/filter/EventListenerKeysFilter.java
> +   List<byte[]> getKeys() {
No need to collect.

2025-02-21 11:48 UTC, pruivo commented on server/resp/src/main/java/org/infinispan/server/resp/filter/EventListenerKeysFilter.java
>        this(keys.toArray(Util.EMPTY_BYTE_ARRAY_ARRAY));
I would use this constructor everywhere and get rid of `public EventListenerKeysFilter(byte[][] keys)`. It seems the RESP server code invokes `List.toArray()` every time this filter is used.

2025-02-21 11:48 UTC, pruivo commented on server/resp/src/main/java/org/infinispan/server/resp/filter/RespTypeFilterConverter.java
>     byte ordinal() {
I'm wondering why not sending the add the Proto annotation to the enum and sending it?

2025-02-21 11:48 UTC, pruivo commented on server/resp/src/main/java/org/infinispan/server/resp/json/JSONUtil.java
> +   // TODO remove
just do it! :smile:

2025-02-21 11:48 UTC, pruivo commented on server/resp/src/main/java/org/infinispan/server/resp/json/JsonSetFunction.java
> +   final boolean xx;
not related to the change, but how am I suppose to know what `xx` and `nx` mean!?

2025-02-25 12:37 UTC, ryanemerson commented on core/src/main/java/org/infinispan/reactive/publisher/impl/commands/reduction/ReductionPublisherRequestCommand.java
> +   public JGroupsAddress getOrigin() {
The command implements `TopologyAffectedCommand`, so I think is required?

2025-02-25 12:52 UTC, ryanemerson commented on lock/src/main/java/org/infinispan/lock/impl/entries/ClusteredLockValue.java
> +   WrappedMessage getWrappedOwner() {
If we're doing this, I think we should probably change the `ClusteredLockImpl` to explicitly use an Address instead of an `object.`

2025-02-25 13:25 UTC, pruivo commented on lock/src/main/java/org/infinispan/lock/impl/entries/ClusteredLockValue.java
> +   WrappedMessage getWrappedOwner() {
It already does as you cannot overwrite the `originator`.

https://github.com/infinispan/infinispan/blob/7206596b4a0258d0b8f1a20d78259e7f270a81ec/lock/src/main/java/org/infinispan/lock/impl/lock/ClusteredLockImpl.java#L82

@karesti can tell us if she plans to change or support other types of owners.

2025-02-25 13:55 UTC, ryanemerson commented on multimap/src/main/java/org/infinispan/multimap/impl/BaseSetBucket.java
>        }
Without this change the `DistributedMultimapSortedSetCacheTest` fails. The reason is that the collection on the unmarshalled side is never null, due to the generated marshaller code. so we either have to handle this in `SortedSetAggregateFunction` or this method. As `BaseSetBucket#inter` is only called by this function and it is not public, I think the change is ok?

2025-02-25 14:14 UTC, pruivo commented on multimap/src/main/java/org/infinispan/multimap/impl/BaseSetBucket.java
>        }
This test?

https://github.com/infinispan/infinispan/blob/9c470980ee5b277acd7f5e55be44c99dde172a7a/multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapSortedSetCacheTest.java#L138

What is the return value if you replace `null` with an empty list? Would ISPN 15 and the feature branch return the same? 

Weirdly, we allow null in the public API and Javadoc does not mention anything. What does it mean to intercept a set with null?

2025-02-25 15:06 UTC, ryanemerson commented on object-filter/src/main/java/org/infinispan/objectfilter/impl/FilterResultImpl.java
> +            MarshallableArray.unwrap(wrappedSortProjection, new Comparable[0])
> why `MarshallableArray.unwrap(wrappedSortProjection, new Comparable[0])` instead of `MarshallableArray.unwrap(wrappedSortProjection)`?

Good spot! That was an oversight from an older implementation of `MarshallableArray` that always required the second param.


> I'm wondering if we can remove the method `MarshallableArray.unwrap(MarshallableArray<T> wrapper, T[] dest)` or clarify when it should be used.

Unfortunately we do need it in a select number of cases where we need the specific type, e.g. `EntryVersion[]` or we get `ClassCastException`. I have fixed this instance and SMIsMember.

2025-02-25 15:54 UTC, ryanemerson commented on server/resp/src/main/java/org/infinispan/server/resp/filter/EventListenerKeysFilter.java
>        this(keys.toArray(Util.EMPTY_BYTE_ARRAY_ARRAY));
I have updated it so that we always have `public EventListenerKeysFilter(Stream<byte[]> keys) {` except in the case of a single key.

2025-02-25 16:54 UTC, ryanemerson commented on lock/src/main/java/org/infinispan/lock/impl/functions/UnlockFunction.java
> +   Set<WrappedMessage> getRequesters() {
The best we can do is a Stream of `JGroupAddress` as Protostream does not know how to handle `Set<Address> getRequesters()` as the type is abstract.

2025-02-25 17:02 UTC, ryanemerson commented on server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/ClientAddress.java
> +   WrappedMessage getWrappedLocalAddress() {
Making this change causes `TxReaperAndRecoveryTest` to fail as it relies on `PersistentUUID#randomUUID`, so I have updated the code to:

```java
   private static Address newAddress() {
      //test address isn't serializable and we just need an address that doesn't belong to the cluster (simulates a leaver)
      return new JGroupsAddress(org.jgroups.util.UUID.randomUUID());
   }
```

2025-03-07 13:28 UTC, pruivo commented on multimap/src/main/java/org/infinispan/multimap/impl/BaseSetBucket.java
>        }
@ryanemerson nothing makes sense to me anymore :rofl: 

I think the interception with an empty set should return an empty and not everything. 

https://github.com/infinispan/infinispan/blob/a5f6215eb19594600ba46553db258ac9d90d27bf/multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCache.java#L354

The method above can check if `scoredValues` is empty and return an empty list or so. We don't need network calls.

2025-03-07 14:05 UTC, jabolina commented on multimap/src/main/java/org/infinispan/multimap/impl/BaseSetBucket.java
>        }
Yeah, the change should be fine. This comes from the ZSET operations in the RESP as well. The intersect (ZINTER) operation accepts multiple keys to perform the operation in sequence. The `null` collection is pretty much for the first time we invoke the intersect for the first key. We don't use a get (ZRANGE) because the intersection has all these bells for aggregation functions, etc., which makes it easier to implement this way.

The change should be fine, there are some validations to avoid the extra call in case the set is empty on the caller side:

https://github.com/infinispan/infinispan/blob/570ac7b8d4f577ad6d8f3deba4f14ebeeb168ecb/server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/internal/AGGCommand.java#L152-L154