Negative metrics raise exceptions in micrometer+prometheus Closes #13235
infinispan/infinispan pull request #13393
Opened 2024-12-13 14:13 UTC by karesti

Closes #13235

2024-12-13 15:58 UTC, pruivo commented
@karesti is it possible to add a test to prevent future errors? 
AFAIK, the Gauge supports positive and negative values. Do we need to update the metrics in all the Infinispan code?

2024-12-13 19:28 UTC, karesti commented
@pruivo This issue starts with Prometheus + Micrometer in version 1.13.
Apparently counters no longer support negative values, leading to a runtime exception.

I can try to add an additional test but prefer not to block this for now, as I’ve implemented the SPI for actuator.
We should review other cases where we use Micrometer + Prometheus and may provide negative stats that may translate to counters.

2024-12-17 09:59 UTC, pruivo requested changes
The test `SimpleApplicationTests` is failing everywhere (Jenkins, GitHub actions, and in my machine) with `expected: <200 OK> but was: <404 NOT_FOUND>`

2024-12-17 09:59 UTC, pruivo commented on spring/spring-boot-3/it-tests/embedded-tests/pom.xml
> +      </dependency>
duplicated dependencies.

2024-12-17 10:06 UTC, karesti commented on spring/spring-boot-3/it-tests/embedded-tests/pom.xml
> +   </profiles>
I don't know I'm discovering this

2024-12-17 14:13 UTC, merged

2024-12-17 14:14 UTC, pruivo commented
merged! thanks @karesti !