[#13251] Allow for a way to limit request value sizes in the server
infinispan/infinispan pull request #13400
Opened 2024-12-13 22:17 UTC by wburns

Fixes #13251 

Supports RESP, HotRod and Memcached server protocols.

Adds a max byte array size and max key count limits. The former prevents any byte[] read from a client request to never be be allocated if it is larger than the configured size. The max key count limits any collection from being allocated if it is said to contain more than that number of entries.

Also added a check to the RESP number parser to not allow it to go longer than 8 bytes (size of a long).

2024-12-13 22:19 UTC, wburns commented
I also toyed with making a new command for the client to retrieve what the configured maximum values are.. but I am second guessing that feature. Especially as our client would have to then submit in parallel (defeats most of this feature) or we have to do them sequentially. I am still open to how we may want to handle this though.

2024-12-18 17:02 UTC, wburns commented
Added parser and docs, but rethinking again I think we should have a default value that is greater than 0 for these values. Our REST endpoint currently limits an entire request to 10MB, so I think that should work for the byte array at least. And maybe 500 key entries.

2025-01-03 13:51 UTC, pruivo commented on server/core/src/main/java/org/infinispan/server/core/configuration/ProtocolServerConfiguration.java
> +   public static final AttributeDefinition<Integer> MAX_BYTE_ARRAY_SIZE = AttributeDefinition.builder(Attribute.MAX_BYTE_ARRAY_SIZE, 10 * 1024 * 1024).immutable().build();
It should be `ByteQuantity` instead of `Integer`, to use the units in the XML file. 

https://github.com/infinispan/infinispan/blob/fc71f27d2b6f8fd251e14d918b0520e7464af708/commons/all/src/main/java/org/infinispan/commons/util/ByteQuantity.java

2025-01-03 13:51 UTC, pruivo commented on server/core/src/main/java/org/infinispan/server/core/configuration/Attribute.java
> +   MAX_KEY_COUNT,
nitpicking, keep them sorted?

2025-01-03 13:51 UTC, pruivo commented on server/core/src/main/java/org/infinispan/server/core/configuration/ProtocolServerConfiguration.java
> +   public static final AttributeDefinition<Integer> MAX_BYTE_ARRAY_SIZE = AttributeDefinition.builder(Attribute.MAX_BYTE_ARRAY_SIZE, 10 * 1024 * 1024).immutable().build();
The XML attribute name seems longer to me. How about `max-length` instead of `max-byte-array-size` or `max-content-length` so all connectors have the same name?

2025-01-03 13:51 UTC, pruivo commented on server/hotrod/src/test/java/org/infinispan/server/hotrod/test/RemoteTransaction.java
> +   public TestResponse prepare() {
why change `TxResponse` to `TestResponse`?

2025-01-03 13:51 UTC, pruivo commented on server/memcached/src/main/java/org/infinispan/server/memcached/binary/BinaryIntrinsics.java
> +         throw new TooLongFrameException("Array length " + length + " exceeded " + maxArrayLength);
This code seems to be duplicated all over the place (only slightly changing the message). Would it make sense to move it to `server/core` in some util class?

2025-01-03 15:42 UTC, wburns commented on server/core/src/main/java/org/infinispan/server/core/configuration/ProtocolServerConfiguration.java
> +   public static final AttributeDefinition<Integer> MAX_BYTE_ARRAY_SIZE = AttributeDefinition.builder(Attribute.MAX_BYTE_ARRAY_SIZE, 10 * 1024 * 1024).immutable().build();
I had debated making the name the same, however it is different than the max-length provided by the REST endpoint as that is the entire request length and these are limits within a single request. HotRod/RESP/Memcached don't have a notion to tell you the request size ahead of time to validate.

I am fine with changing the names to something else though if you have better suggestions.

2025-01-03 15:43 UTC, wburns commented on server/hotrod/src/test/java/org/infinispan/server/hotrod/test/RemoteTransaction.java
> +   public TestResponse prepare() {
I needed to change if you get an error during prepare it would return a different type which I needed to assert on.

2025-01-03 22:00 UTC, wburns commented on server/memcached/src/main/java/org/infinispan/server/memcached/binary/BinaryIntrinsics.java
> +         throw new TooLongFrameException("Array length " + length + " exceeded " + maxArrayLength);
I kept debating about this, I guess we can. I think I can reduce it down to 4 variants.

2025-01-06 10:13 UTC, pruivo commented on server/core/src/main/java/org/infinispan/server/core/configuration/ProtocolServerConfiguration.java
> +   public static final AttributeDefinition<Integer> MAX_BYTE_ARRAY_SIZE = AttributeDefinition.builder(Attribute.MAX_BYTE_ARRAY_SIZE, 10 * 1024 * 1024).immutable().build();
I see.
`max-length` is the suggestion I have. I'm not sure if it is a better name or not :)

2025-01-06 11:24 UTC, pruivo requested changes

2025-01-06 11:24 UTC, pruivo commented on server/resp/src/main/java/org/infinispan/server/resp/BaseRespDecoder.java
> +   protected <T> List<T> allocList(int size, int maxKeyCount) {
unused?

2025-01-06 11:24 UTC, pruivo commented on server/runtime/src/main/resources/schema/infinispan-server-15.2.xsd
> +            <xs:attribute name="max-byte-array-size" type="xs:int">
Add the source code default to the `attribute`.
Not sure if the name is correct, but something like this should work:
```suggestion
            <xs:attribute name="max-byte-array-size" type="xs:int" default="${ProtocolServer.max-byte-array-size}">
```

2025-01-06 11:24 UTC, pruivo commented on server/runtime/src/test/resources/configuration/versions/15.1.xml
> +                              external-host="external" external-port="12345" max-key-count="13" max-byte-array-size="1027">
It must be changed in file 15.2.xml and rolled back in file 15.1.xml.

2025-01-06 11:24 UTC, pruivo commented on server/memcached/src/test/java/org/infinispan/server/memcached/test/MemcachedRequestLimitTest.java
> + * Tests Memcached protocol functionality against Infinispan Memcached server.
remove or update javadoc?

2025-01-06 11:24 UTC, pruivo commented on server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodRequestLimitTest.java
> + * @since 15.1
```suggestion
 * @since 15.2
```

2025-01-27 13:52 UTC, tristantarrant commented on server/core/src/main/java/org/infinispan/server/core/configuration/ProtocolServerConfiguration.java
> +   public static final AttributeDefinition<Integer> MAX_BYTE_ARRAY_SIZE = AttributeDefinition.builder(Attribute.MAX_BYTE_ARRAY_SIZE, 10 * 1024 * 1024).immutable().build();
let's use the same for every protocol. Any differences can be highlighted in the docs

2025-01-28 22:03 UTC, wburns commented
Updated to use new form of limiting the entire request length for all endpoints.

2025-01-29 17:56 UTC, wburns commented
Oops forgot to update to 15.2 for various things.. updating.

2025-01-29 20:45 UTC, wburns commented
The new approach should be ready to review now.

2025-02-04 08:07 UTC, tristantarrant commented
@wburns can you please rebase ?

2025-02-04 18:40 UTC, wburns commented
Rebased.

2025-02-05 07:07 UTC, tristantarrant commented
Tons of failure in Hot Rod client tx tests

2025-02-05 20:12 UTC, wburns commented
Tests should be in better shape now, waiting on CI to confirm though.

2025-02-05 22:30 UTC, wburns commented
Still some failures left. Also I am not sure about the ByteParser not allowing negative numbers. I think it would be nice, but I need to think about it a bit more and discuss possibly.

2025-02-05 23:31 UTC, wburns commented
It should all pass now.
Note that I changed ByteQuantity to support negative values. I can revert that but then I need to change other places.

2025-02-26 11:47 UTC, tristantarrant requested changes

2025-02-26 11:47 UTC, tristantarrant commented on server/hotrod/src/main/java/org/infinispan/server/hotrod/configuration/Attribute.java
> +   MAX_CONTENT_LENGTH,
`MAX_CONTENT_LENGTH` should be in `org.infinispan.server.core.configuration.Attribute`. Remove the one in `org.infinispan.server.configuration.rest.Attribute`.

2025-02-26 11:47 UTC, tristantarrant commented on server/core/src/main/java/org/infinispan/server/core/configuration/ProtocolServerConfiguration.java
> +   public static final AttributeDefinition<String> MAX_CONTENT_LENGTH = AttributeDefinition.builder("max-content-length", "10MB", String.class)
Use a constant in `org.infinispan.server.core.configuration.Attribute`

2025-02-26 11:47 UTC, tristantarrant commented on server/hotrod/src/main/java/org/infinispan/server/hotrod/logging/Log.java
> +public interface Log extends org.infinispan.server.core.logging.Log {
Please don't change this. The logging processor unfolds all inherited classes, resulting in huge implementations.

2025-02-26 11:47 UTC, tristantarrant commented on server/memcached/src/main/java/org/infinispan/server/memcached/logging/Log.java
> +public interface Log extends org.infinispan.server.core.logging.Log {
See my comment above on logger inheritance.

2025-02-26 15:20 UTC, wburns commented on server/hotrod/src/main/java/org/infinispan/server/hotrod/logging/Log.java
> +public interface Log extends org.infinispan.server.core.logging.Log {
Honestly, it seems like a bug to me that we have a server core logger and each of the specific protocol Log implementations. This means you have to have both loggers in the class to handle the case of a shared log message versus a specific protocol one, but I will add the Log instance to each of the classes that need it as I assume we don't want to duplicate the message in each protocol Log instance.

2025-02-26 15:25 UTC, wburns commented on server/core/src/main/java/org/infinispan/server/core/configuration/ProtocolServerConfiguration.java
> +   public static final AttributeDefinition<String> MAX_CONTENT_LENGTH = AttributeDefinition.builder("max-content-length", "10MB", String.class)
I will consolidate this like the max content length attribute

2025-02-27 00:50 UTC, wburns commented
Addressed comments, thanks @tristantarrant !

2025-03-03 16:05 UTC, wburns commented
Rebased

2025-03-07 23:04 UTC, wburns commented
This one should be ready if someone wants to take another look, thanks!

2025-03-09 09:22 UTC, tristantarrant commented
`org.infinispan.server.hotrod.test.HotRodRequestLimitTest#testPipelineWriteSecondOperationTooLarge` is flaky

2025-03-10 22:41 UTC, wburns commented
Rebased and updated so the test should work reliably now.

2025-03-11 08:30 UTC, merged

2025-03-11 08:30 UTC, tristantarrant commented
Merged, thanks