ISPN-12044 CLI performance tool
infinispan/infinispan pull request #8500
Opened 2020-06-24 13:59 UTC by tristantarrant

https://issues.redhat.com/browse/ISPN-12044

2020-09-30 12:50 UTC, tristantarrant commented
This is now ready

2020-10-01 15:09 UTC, karesti requested changes
small comments, I guess @oraNod may want to grab a look to docs as well?

2020-10-01 15:09 UTC, karesti commented on cli/cli-client/src/main/java/org/infinispan/cli/benchmark/HttpBenchmark.java
> +      cm = RestClient.forConfiguration(builder.build());
cm variable name related to cacheManager but the RestClient returns a restClient. I would rename this to avoid confusion with the HotrodBenchmark

2020-10-01 15:09 UTC, karesti commented on cli/cli-client/src/main/java/org/infinispan/cli/benchmark/HttpBenchmark.java
> +      if (uncheckedAwait(cache.exists()).getStatus() == 404) {
same here, it's not a cache but the restCacheClient

2020-10-02 10:19 UTC, oraNod commented on cli/cli-client/src/main/resources/help/benchmark.adoc
> +The benchmark can be performed both for HTTP and for Hot Rod: the mode is determined by the protocol of the supplied URI.
@tristantarrant I'm curious about "the mode is determined by the protocol of the supplied URI." How does the protocol determine the mode? Are there some benchmark modes that do not apply for certain protocols?

2020-10-02 10:19 UTC, oraNod commented on cli/cli-client/src/main/resources/help/benchmark.adoc
> +How verbose the output should be. One of SILENT, NORMAL, EXTRA. Defaults to NORMAL.
There seems to be no difference in the output when I set different verbosity levels.

2020-10-02 10:19 UTC, oraNod commented on cli/cli-client/src/main/resources/help/benchmark.adoc
> +The size of the key. Defaults to 16 bytes.
The size unit for the value is byte? "Sets the size, in bytes, of the key.

2020-10-02 10:19 UTC, oraNod commented on cli/cli-client/src/main/resources/help/benchmark.adoc
> +How long each iteration should take. Defaults to 10s.
The time unit is seconds? "Sets the amount of time, in seconds, that each iteration takes."

2020-10-06 13:49 UTC, tristantarrant commented
@oraNod @karesti I believe I've addressed the issues

2020-10-06 16:07 UTC, oraNod commented
@tristantarrant hey, I pushed a commit with suggested doc edits. feel free to revert, squash, whatever. also I noticed you removed the fork option from the command but it was still in the help text so I removed it there. cheers.

2020-10-12 07:24 UTC, tristantarrant commented
@oraNod I've squashed your commit into mine
@karesti I've addressed most comments, aside from those related to the BenchmarkOutputFormat which I've explained

2020-10-12 09:40 UTC, oraNod approved these changes
LGTM

2020-10-13 10:22 UTC, merged