ISPN-12177 Persist IRAC version during shutdown
infinispan/infinispan pull request #8680
Opened 2020-09-10 10:51 UTC by pruivo

https://issues.redhat.com/browse/ISPN-12177

2020-09-28 08:30 UTC, tristantarrant commented
Conflicts

2020-10-22 16:05 UTC, wburns requested changes
So I see where it loads from the file, but isn't there supposed to be something to read the state from the other site? Or is that handled elsewhere?

And what about if we have data in a store, guessing that is a different PR?

2020-10-22 17:45 UTC, pruivo commented on core/src/main/java/org/infinispan/commands/irac/IracMetadataRequestCommand.java
>              ", topologyId=" + topologyId +
not really. It makes sure the node has at least that topology installed before handling the executing the command.

2020-10-22 17:47 UTC, wburns commented on core/src/main/java/org/infinispan/commands/irac/IracMetadataRequestCommand.java
>              ", topologyId=" + topologyId +
Shouldn't it be part of the `readFrom` and `writeTo` though?

2020-10-22 17:48 UTC, pruivo commented on core/src/main/java/org/infinispan/container/versioning/irac/TopologyIracVersion.java
> +      Matcher m = Pattern.compile(REGEX).matcher(s);
right!

2020-10-22 17:48 UTC, pruivo commented on core/src/main/java/org/infinispan/container/versioning/irac/TopologyIracVersion.java
> +      return String.format(FMT, topologyId, version);
I've spent too much time in python xD

2020-10-22 17:54 UTC, pruivo commented
Each node, when a rebalance happends, broadcast its version state to all other nodes (see `org.infinispan.container.versioning.irac.DefaultIracVersionGenerator#onTopologyChange()`)

2020-10-22 17:56 UTC, pruivo commented
About the cache store, it uses the version in the context to generate a new higher version. Example, for non-tx caches: https://github.com/infinispan/infinispan/pull/8680/files#diff-8f85a96763cdc57d2a36e8a8b873178ab509a3083766c6d2ff9bb56a07a1a2c6R205

this covers "all" scenarios except if you use SKIP_CACHE_LOAD + !preload  + !conditional_write

2020-10-22 18:03 UTC, pruivo commented
updated & rebased

2020-10-22 19:27 UTC, pruivo commented on core/src/main/java/org/infinispan/commands/irac/IracMetadataRequestCommand.java
>              ", topologyId=" + topologyId +
no, the previous code was incorrect.
The `CacheRpcCommandExternalizer` [1] invokes the `ReplicableCommandExternalizer` [2] and the latter sends the topology id.

[1] https://github.com/infinispan/infinispan/blob/master/core/src/main/java/org/infinispan/marshall/exts/CacheRpcCommandExternalizer.java#L142
[2] https://github.com/infinispan/infinispan/blob/master/core/src/main/java/org/infinispan/marshall/exts/ReplicableCommandExternalizer.java#L82

2020-10-23 10:40 UTC, pruivo commented
fixed test failure

2020-10-23 15:38 UTC, merged

2020-10-23 15:38 UTC, wburns commented
Integrated into master, thanks @pruivo !

2020-10-23 17:11 UTC, pruivo commented
yey!  thanks @wburns !