ISPN-12402 + ISPN-12184 Multiple single-port endpoints and explicit/implicit fixes
infinispan/infinispan pull request #8775
Opened 2020-10-13 14:46 UTC by tristantarrant

This PR introduces the ability to have multiple single-port endpoints. It also allows disabling admin features (CLI/Console) per-endpoint. Additionally it fixes an issue where it was not really respecting explicit authentication mechanisms.

https://issues.redhat.com/browse/ISPN-12184
https://issues.redhat.com/browse/ISPN-12402

2020-10-22 16:05 UTC, pruivo requested changes
minor suggestions.

2020-10-22 16:16 UTC, pruivo commented
```
17:06:52,033 INFO  (ForkJoinPool.commonPool-worker-3) [org.infinispan.SERVER] ISPN080018: Protocol HotRod (internal)
17:06:52,115 INFO  (main) [org.infinispan.SERVER] ISPN080018: Protocol REST (internal)
17:06:52,285 INFO  (main) [org.infinispan.SERVER] ISPN080004: Protocol SINGLE_PORT listening on 127.0.0.1:11222
17:06:52,285 INFO  (main) [org.infinispan.SERVER] ISPN080034: Server 'pedro-desktop-17255' listening on http://127.0.0.1:11222
17:06:52,302 INFO  (ForkJoinPool.commonPool-worker-3) [org.infinispan.SERVER] ISPN080018: Protocol HotRod (internal)
17:06:52,335 INFO  (main) [org.infinispan.SERVER] ISPN080018: Protocol REST (internal)
17:06:52,664 INFO  (main) [org.infinispan.SERVER] ISPN080004: Protocol SINGLE_PORT listening on 192.168.2.100:13333
17:06:52,664 INFO  (main) [org.infinispan.SERVER] ISPN080034: Server 'pedro-desktop-17255' listening on http://192.168.2.100:13333
17:06:52,664 INFO  (main) [org.infinispan.SERVER] ISPN080001: Infinispan Server 12.0.0-SNAPSHOT started in 5329ms
```

* I think there is a verb missing in  `ISPN080018` message
* `ISPN080004: Protocol SINGLE_PORT ` IMO, it would be nice to add the `socket-binding` name to the log message, like
`Protocol SINGLE_PORT (<socket-binding>) listening on 127.0.0.1:11222`

2020-10-23 08:53 UTC, pruivo requested changes
The JSON writer is broken and `JsonSerializationTest` is failing. 

It is generating the following json
```
"endpoints": {
      "endpoints": {
        "socket-binding": "default",
        "security-realm": "default",
        "hotrod-connector": {
```
 IMO, it should be an array of endpoints since you can have multiple endpoints now. 
```
"endpoints": [
      {
        "socket-binding": "default",
        "security-realm": "default",
        "hotrod-connector": {
```

I guess (not tested!) the easy fix would be `elements.add(endpoints);` in `ServerConfiguration` change to `elements.addAll(endpoints.subElements());`

2020-10-23 08:53 UTC, pruivo commented on server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointConfiguration.java
> + * @since 10.0
nitpick:
```suggestion
 * @since 12.0
```

2020-11-05 18:41 UTC, pruivo requested changes
minor comment.

2020-11-05 18:41 UTC, pruivo commented on server/runtime/src/main/java/org/infinispan/server/Server.java
> +                  System.err.println(t.getMessage());
I guess this requires a proper log message :)

2020-11-05 18:41 UTC, pruivo commented on server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationParser.java
> +
nitpick: remove empty line

2020-11-05 18:41 UTC, pruivo commented on server/tests/src/test/resources/configuration/endpoints/default-auth-implicit.xml
> +   <hotrod-connector name="hotrod"/>
nit: you could remove the connector name for hotrod & rest

2020-11-05 18:43 UTC, pruivo commented
@tristantarrant there are test failures, probably related:
* RestServerResource (NPE)
* CliIT

2020-11-05 18:53 UTC, pruivo commented
offtopic: while testing "admin" and "metric-auth", it looks like the `disconnect` is broken. `connection = null` is missing in `org.infinispan.cli.impl.ContextImpl#disconnect()`. I guess it can be fixed here :) it is just one line.

```
pedro-desktop-53750@cluster//containers/default]> disconnect 
[pedro-desktop-53750@cluster//containers/default]> disconnect 
[pedro-desktop-53750@cluster//containers/default]> disconnect 
[pedro-desktop-53750@cluster//containers/default]> disconnect -h
Usage: disconnect [<options>]
Disconnects from a remote server

Options:
  -h, --help

[pedro-desktop-53750@cluster//containers/default]> disconnect 
[pedro-desktop-53750@cluster//containers/default]> ls
Could not connect to server: java.io.InterruptedIOException: executor rejected
[pedro-desktop-53750@cluster//containers/default]> ls
Could not connect to server: java.io.InterruptedIOException: executor rejected
[pedro-desktop-53750@cluster//containers/default]> cd 
The name of the subsystem/item is required for this command.
[pedro-desktop-53750@cluster//containers/default]> ls
Could not connect to server: java.io.InterruptedIOException: executor rejected
[pedro-desktop-53750@cluster//containers/default]> cd /
[pedro-desktop-53750@cluster/]> ls
containers
cluster
server
[pedro-desktop-53750@cluster/]> cd containers
[pedro-desktop-53750@cluster//containers]> ls
default
[pedro-desktop-53750@cluster//containers]> cd default
Could not connect to server: java.io.InterruptedIOException: executor rejected
```

2020-11-06 14:32 UTC, tristantarrant commented
@pruivo I've addressed all issues I believe

2020-11-06 15:50 UTC, pruivo approved these changes

2020-11-09 13:00 UTC, merged

2020-11-09 13:01 UTC, pruivo commented
integrated! thanks @tristantarrant !