[PREVIEW] Add a cache.query() API
infinispan/infinispan pull request #8792
Opened 2020-10-19 12:38 UTC by tristantarrant

https://issues.redhat.com/browse/query-api

Just a quick hack to show a cheap way to get a better query API

2020-10-19 12:54 UTC, gustavonalle commented
This is the end goal for query, but I think @anistor was working on moving the Query interface to ```query-core``` first, and remove the query-dsl module in the process. Plus, we currently have 2 ```Search``` objects, one for ```query-core``` and another for ```query```, also we can't pick the QueryEngine from ```query-core``` as it'd only be executing non-indexed queries

2020-10-19 12:56 UTC, tristantarrant commented
This was just a quick hack: it doesn't work, but it shows what we could
have.

On Mon, Oct 19, 2020 at 2:55 PM Gustavo <notifications@github.com> wrote:

> This is the end goal for query, but I think @anistor
> <https://github.com/anistor> was working on moving the Query interface to
> query-core first, and remove the query-dsl module in the process. Plus,
> we currently have 2 Search objects, one for query-core and another for
> query, also we can't pick the QueryEngine from query-core as it'd only be
> executing non-indexed queries
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/infinispan/infinispan/pull/8792#issuecomment-712136351>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAC72HQORKJMJDLDSOHUTSTSLQZLHANCNFSM4SWC2QRA>
> .
>

2020-10-19 13:00 UTC, gustavonalle commented
API-wise that's what I envisioned  :+1:

2020-10-19 14:12 UTC, yrodiere commented on commons/all/src/main/java/org/infinispan/commons/api/QueryResult.java
> +   OptionalLong hitCount();
You may want something more complex, to allow for approximate hit counts. See https://docs.jboss.org/hibernate/search/6.0/reference/en-US/html_single/#search-dsl-query-total-hits-threshold .

2020-10-20 09:22 UTC, karesti commented
@tristantarrant This is coming back to all the discussion we had about caches being 'Queryable' 'transactional' and so on a couple of years ago. At first this is something I wanted to do but this is why the module of api was created and the idea of making evolve the api from there.
Why not this, IMO moving to commons and doing it this way might be a finally a good thing. My only concern is that we discussed a lot, like a lot, about this in the past and arrived to a consensus to try it in another manner. The fact is that the target we had two years ago is not moving forward as expected because we struggle to make it happen (too many things to do, not enough time and resources allocated for this)
I'd prefer to had a discussion about this again instead of making this forward in a PR

2020-10-20 09:25 UTC, tristantarrant commented
@karesti this is just a quick and dirty way to finally get the query API into our legacy cache API without introducing something completely new.
The new API is definitely where we want to go, but as you mention, it is not likely to happen soon.

2020-10-20 09:30 UTC, gustavonalle commented
My $0.02: we should first stabilize the unified, simplified, query API in ```query``` in ISPN 12, since as you remember, we are coming from 3 different query APIs with lots of leaks and also rewrite of Hibernate Search in between. After that we can think of evolving it to move into cache

2020-10-20 11:15 UTC, anistor commented
Exactly, the 'Search endpoint' does not go anywhere soon. At least not in 12.  So let's do the bare minimum, which @gustavonalle mentions above, and was discussed already about1-2 months ago. This PR is just meant to showcase that little API, not to be an actual working branch.  I've done myself what Tristan did here (actually about 95% identical api, but I'll mend it to make it 100% identical), but additionally it has working tests, module reorg and complete builder DSL whipeout. Please have a bit of patience.

2020-10-20 11:19 UTC, anistor requested changes
I'll have a working PR that does this, having both query methods, via ```Search``` endpoint and also via ```Cache``` api. We'll decide by 12.0.0.Final which of the 2 is Final-worthy.   As for the general new infinispan api, that discussion should not be extended too long here.

2020-10-20 11:30 UTC, gustavonalle commented
> We'll decide by 12.0.0.Final which of the 2 is Final-worthy

Oh no, the query APIs multiplied again :)

2020-10-20 14:00 UTC, anistor commented
It's a virus

2020-10-20 14:03 UTC, anistor commented
I don't like it migrating to commons, but such is life ...

2020-10-20 16:58 UTC, gustavonalle commented
> I don't like it migrating to commons, but such is life ...

Nothing against it, but I don't think we're doing a favour to users if we, on top of everything that's already changed, we add a forked search API in ISPN 12 (part in commons, part in query). IMHO this should be postponed to 13 and beyond.

2020-11-06 12:48 UTC, closed without merging