ISPN-12398 Update Backup manager resource names and directories
infinispan/infinispan pull request #8908
Opened 2020-12-03 12:42 UTC by ryanemerson

https://issues.redhat.com/browse/ISPN-12398

2020-12-04 09:30 UTC, oraNod commented on cli/src/main/java/org/infinispan/cli/commands/Backup.java
> +      @OptionList(description = "Comma separated list of templates to include, '*' indicates all available",
```suggestion
      @OptionList(description = "Comma separated list of cache templates to include, '*' indicates all available",
```

2020-12-04 09:30 UTC, oraNod commented on cli/src/main/resources/help/backup.adoc
> +Lists templates to back up. Use '*' to back up all templates.
```suggestion
Lists cache templates to back up. Use '*' to back up all templates.
```

2020-12-04 09:30 UTC, oraNod commented on cli/src/main/resources/help/backup.adoc
> +*--templates*='config1,config2,...'::
Should this be 'template1,template2,...' ?

2020-12-04 09:30 UTC, oraNod commented on cli/src/main/resources/help/backup.adoc
> +*--tasks*='script1,script2,...'::
```suggestion
*--tasks*='task1,task2,...'::
```

2020-12-04 09:30 UTC, oraNod commented on cli/src/main/resources/help/backup.adoc
> +Lists tasks to back up. Use '*' to back up all tasks.
```suggestion
Lists server tasks to back up. Use '*' to back up all tasks.
```

2020-12-04 09:30 UTC, oraNod commented on cli/src/main/resources/help/backup.adoc
> +Lists templates to restore. Use '*' to restore all templates from the backup archive.
```suggestion
Lists cache templates to restore. Use '*' to restore all templates from the backup archive.
```

2020-12-04 09:30 UTC, oraNod commented on cli/src/main/resources/help/backup.adoc
> +Lists tasks to restore. Use '*' to restore all tasks from the backup archive.
```suggestion
Lists server tasks to restore. Use '*' to restore all tasks from the backup archive.
```

2020-12-04 09:30 UTC, oraNod commented on cli/src/main/resources/help/backup.adoc
> +*--tasks*='script1,script2,...'::
```suggestion
*--tasks*='task1,task2,...'::
```

2020-12-04 09:30 UTC, oraNod commented on documentation/src/main/asciidoc/topics/backup_resources.adoc
> +|Specifies either an array of templates to back up or `*` for all templates.
```suggestion
|Specifies either an array of cache templates to back up or `*` for all templates.
```

2020-12-04 09:30 UTC, oraNod commented on documentation/src/main/asciidoc/topics/backup_resources.adoc
> +|Specifies either an array of script names to back up or `*` for all tasks.
```suggestion
|Specifies either an array of server tasks to back up or `*` for all tasks.
```

2020-12-04 09:30 UTC, oraNod commented on documentation/src/main/asciidoc/topics/proc_cli_backup_creating.adoc
> +* Back up only caches and templates.
```suggestion
* Back up only caches and cache templates.
```

2020-12-04 09:30 UTC, oraNod commented on documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc
> +templates, counters, Protobuf schemas, tasks, and so on) currently
```suggestion
cache templates, counters, Protobuf schemas, server tasks, and so on) currently
```

2020-12-04 09:30 UTC, oraNod commented on documentation/src/main/asciidoc/topics/ref_rest_clusters.adoc
> +Create backup archives, `application/zip`, that contain resources (caches, templates, counters, Protobuf schemas, tasks,
```suggestion
Create backup archives, `application/zip`, that contain resources (caches, cache templates, counters, Protobuf schemas, server tasks,
```

2020-12-04 10:13 UTC, ryanemerson commented
All addressed, thanks @oraNod

2020-12-04 10:23 UTC, oraNod approved these changes
LGTM. Thanks, Ryan!

2020-12-08 21:26 UTC, karesti requested changes
may this change have impacted some tests ?

2020-12-10 12:38 UTC, tristantarrant commented
@ryanemerson you need to fix the path in BackupManagerIT

2020-12-10 15:32 UTC, ryanemerson commented
Should be good now

2020-12-10 20:24 UTC, merged

2020-12-10 20:24 UTC, wburns commented
Integrated into master, thanks @ryanemerson !