ISPN-12584 Protobuf serialization in library mode with spring starter
infinispan/infinispan pull request #8951
Opened 2020-12-22 12:53 UTC by danberindei

https://issues.redhat.com/browse/ISPN-12584

Make JavaSerializationMarshaller the default marshaller even when
the configXml property is present.
Users can still change it if they want protostream marshalling
and they aren't storing Spring sessions in the cache.

2020-12-23 21:03 UTC, karesti commented
@danberindei I'm not sure about 'Users can still change it if they want protostream marshalling'
NullValue that is supported by Spring caches, was not working with protobuf. I think the issue was in library and remote, and easily being reproduced by the simple tutorials.

2020-12-23 21:04 UTC, karesti requested changes
not sure about it...

2021-02-01 12:33 UTC, danberindei commented
> @danberindei I'm not sure about 'Users can still change it if they want protostream marshalling'
> NullValue that is supported by Spring caches, was not working with protobuf. I think the issue was in library and remote, and easily being reproduced by the simple tutorials.

@karesti ok, maybe not protostream, maybe some other custom marshaller that does support `NullValue` :)

I didn't mean that this PR makes protostream marshalling work, I only meant that the user can still override the default marshaller, and this PR only changes the default when the `configXml` property is set.

2021-02-03 11:20 UTC, karesti approved these changes

2021-02-03 11:21 UTC, merged