ISPN-11914 ServerRunMode.FORKED should use by default the server folder
infinispan/infinispan pull request #8966
Opened 2021-01-07 17:57 UTC by diegolovison

2021-04-23 15:01 UTC, diegolovison commented
run performance tests please

2021-04-23 15:24 UTC, diegolovison commented
run performance tests please

2021-04-23 15:27 UTC, diegolovison commented
run performance tests please

2021-04-23 17:19 UTC, diegolovison commented
run performance tests please

2021-04-23 19:46 UTC, diegolovison commented
run performance tests please

2021-05-04 14:03 UTC, rhusar requested changes
Needs a rebase now :-)

2021-05-04 14:03 UTC, rhusar commented on server/testdriver/core/src/main/java/org/infinispan/server/test/core/ForkedInfinispanServerDriver.java
> +            throw new UncheckedIOException("Cannot copy the server to temp folder", e);
s/folder/directory :-)

2021-05-04 15:56 UTC, diegolovison commented
@rhusar please review

2021-05-27 15:27 UTC, merged

2021-06-17 13:02 UTC, rhusar commented
@diegolovison Is this the intended design Diego? While this solves some of the log isolation problems, this copies now cca 110 MB of data per test class per cluster member; we have e.g. 10 test classes, each should run against 2 node infinispan server cluster so its more than 2 GB of temporary data to manage. Opened https://issues.redhat.com/browse/ISPN-13109

2021-06-17 13:03 UTC, rhusar commented
@diegolovison Also, have you tested this on windows? It seems to have broken windows support again - opened https://issues.redhat.com/browse/ISPN-13107 and will try to debug this and submit a PR for that as well.

2021-06-17 13:21 UTC, diegolovison commented
@rhusar the goal of this PR was to use the current server instead of one provided by the user. If you have two servers now and had two servers before the amount of disk space is/was the same.