ISPN-12684 Lazy start SearchMapping for protobuf caches
infinispan/infinispan pull request #9029
Opened 2021-02-02 14:45 UTC by gustavonalle

https://issues.redhat.com/browse/ISPN-12684

2021-02-02 14:53 UTC, gustavonalle commented
Marking as preview to let CI run

2021-02-03 15:58 UTC, gustavonalle commented
Fixed tests, ready for review

2021-02-19 17:35 UTC, tristantarrant requested changes
Just one minor change

2021-02-19 17:35 UTC, tristantarrant commented on remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LazySearchMapping.java
> +                  throw new CacheConfigurationException("The declared indexed type '" + typeName + "' is not known. Please register its proto schema file first.");
I'd prefer an i18n exception here

2021-02-19 18:08 UTC, gustavonalle commented on remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LazySearchMapping.java
> +                  throw new CacheConfigurationException("The declared indexed type '" + typeName + "' is not known. Please register its proto schema file first.");
fixed!

2021-02-20 16:38 UTC, merged

2021-02-20 16:38 UTC, tristantarrant commented
Merged ,thanks