ISPN-12774 Credential store support example for datasource is incomplete
infinispan/infinispan pull request #9084
Opened 2021-02-23 21:20 UTC by gustavolira

https://issues.redhat.com/browse/ISPN-12774

2021-02-24 19:34 UTC, oraNod commented
@gustavolira Thanks for the PR! Can we also take this as an opportunity to improve that issue you noted with `<clear-text-credential clear-text="secret"/>` ?

If I understand correctly s/secret/secret1234! https://github.com/infinispan/infinispan/pull/8841/files#diff-04d5620d7c62290027d79c47b8a960d6e541b720335474afdc3c164add6df333R7

2021-02-24 19:55 UTC, gustavolira commented
> @gustavolira Thanks for the PR! Can we also take this as an opportunity to improve that issue you noted with `<clear-text-credential clear-text="secret"/>` ?
> 
> If I understand correctly s/secret/secret1234! https://github.com/infinispan/infinispan/pull/8841/files#diff-04d5620d7c62290027d79c47b8a960d6e541b720335474afdc3c164add6df333R7

@oraNod  Sure, I'm on it.

2021-02-24 21:09 UTC, gustavolira commented
> > @gustavolira Thanks for the PR! Can we also take this as an opportunity to improve that issue you noted with `<clear-text-credential clear-text="secret"/>` ?
> > If I understand correctly s/secret/secret1234! https://github.com/infinispan/infinispan/pull/8841/files#diff-04d5620d7c62290027d79c47b8a960d6e541b720335474afdc3c164add6df333R7
> 
> @oraNod Sure, I'm on it.

@oraNod done

2021-02-25 12:12 UTC, oraNod commented on cli/src/main/resources/help/credentials.adoc
> +`credentials ls -p "secret1234!"` +`
```suggestion
`credentials ls -p "secret1234!"` +
```

2021-02-25 12:16 UTC, oraNod commented on cli/src/main/resources/help/credentials.adoc
> +This command also sets "secret1234!" as the password for the credential keystore, this value should match with the value present in the server configuration like:
```suggestion
This command also sets "secret1234!" as the password for the credential keystore, which must match the password in the server configuration:
```

2021-02-25 12:19 UTC, oraNod requested changes
@gustavolira Thanks for adding that detail about the password. For the sake of completeness, could you also update the password in the server config example so that it matches the CLI docs? 

https://github.com/infinispan/infinispan/blob/537d58b53f058de1ee9e6e975fc99b0e8d4f4c50/documentation/src/main/asciidoc/topics/config_examples/server_credentials.xml#L7

2021-02-25 13:56 UTC, oraNod approved these changes
LGTM

2021-02-25 13:56 UTC, merged

2021-02-25 13:56 UTC, oraNod commented
Merged. Thanks @gustavolira Can you please create a backport for 12.0.x?