ISPN-12873 Fix empty XML from the REST cache config endpoint
infinispan/infinispan pull request #9168
Opened 2021-03-23 14:34 UTC by tristantarrant

https://issues.redhat.com/browse/ISPN-12873

2021-03-25 11:28 UTC, gustavonalle requested changes

2021-03-25 11:28 UTC, gustavonalle commented on server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
> +               return CompletableFuture.completedFuture(responseBuilder.status(INTERNAL_SERVER_ERROR).build());
```suggestion
               return CompletableFuture.completedFuture(responseBuilder.status(INTERNAL_SERVER_ERROR).entity(Util.getRootCause(e)).build());
```

2021-03-25 16:23 UTC, gustavonalle commented
stopped by the checkstyle police :police_car:

2021-03-30 11:57 UTC, tristantarrant commented
Fixed

2021-03-31 15:35 UTC, tristantarrant commented on server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
> +               return CompletableFuture.completedFuture(responseBuilder.status(INTERNAL_SERVER_ERROR).build());
It's there now

2021-03-31 16:24 UTC, pruivo commented on server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
> +public class
revert change?

2021-04-01 14:09 UTC, tristantarrant commented on server/rest/src/test/java/org/infinispan/rest/resources/CacheV2ResourceTest.java
> +public class
Fixed

2021-04-01 14:36 UTC, merged

2021-04-01 14:36 UTC, pruivo commented
integrated! thanks @tristantarrant !