ISPN-7021 Fix SiteProviderTopologyChangeTest
infinispan/infinispan pull request #9276
Opened 2021-04-28 17:23 UTC by pruivo

* fix random failures in SiteProviderTopologyChangeTest

2021-06-21 14:29 UTC, ryanemerson commented
There are two xsite failures, are they related to your `XSiteStateTransferManagerImpl.java ` changes?

2021-07-21 15:29 UTC, danberindei requested changes

2021-07-21 15:29 UTC, danberindei commented on core/src/test/java/org/infinispan/xsite/statetransfer/failures/SiteProviderTopologyChangeTest.java
> +      topologyManager.unblockAll();
IMO `unblockAll()` doesn't make sense without `stopBlocking()`, so it should either be controlled by a parameter or the default behaviour of `stopBlocking()`.

Currently `stopBlocking()` logs an error when there are unblocked topologies in the queue, which I think (now) is not a good compromise: it should either throw an exception or unblock all queued topologies (and log only a debug message).

2021-07-21 16:00 UTC, pruivo commented on core/src/test/java/org/infinispan/xsite/statetransfer/failures/SiteProviderTopologyChangeTest.java
> +@Test(groups = "xsite", testName = "xsite.statetransfer.failures.SiteProviderTopologyChangeTest")
no. in this PR I'm *trying* to fix the sender side.
ISPN-6228 is about the receiving site.

2021-07-21 16:47 UTC, danberindei commented on core/src/test/java/org/infinispan/xsite/statetransfer/failures/SiteProviderTopologyChangeTest.java
> +@Test(groups = "xsite", testName = "xsite.statetransfer.failures.SiteProviderTopologyChangeTest")
I was worried that if ISPN-6228 isn't resolved then the random failures will appear again, but if you think ISPN-7021 was the real cause then it's fine. Maybe you should cross that line in the ISPN-6228 description, though ;)

2021-07-22 09:35 UTC, pruivo commented on core/src/test/java/org/infinispan/xsite/AbstractTwoSitesTest.java
> +            .stateTransfer().maxRetries(5).waitTime(1000)
the test does not wait for all retries.
one of the causes of random failure was the sender site giving up too soon. The test only waits for the cluster state transfer and cross-site state transfer to complete.

2021-09-06 09:50 UTC, pruivo commented
closing this for now. Probably need a new impl for xsite state transfer

2021-09-06 09:50 UTC, closed without merging