ISPN-13052 Hot Rod Java client doc updates
infinispan/infinispan pull request #9335
Opened 2021-05-20 11:16 UTC by oraNod

https://issues.redhat.com/browse/ISPN-13052

2021-05-20 14:01 UTC, pruivo requested changes

2021-05-20 14:32 UTC, oraNod commented on documentation/src/main/asciidoc/topics/proc_configuring_hotrod_java_clients.adoc
> +      boolean started = rcm.getChannelFactory().getNumActive() > 0;
This actually came from the QE team. Maybe let's just remove it if it doesn't make that much sense.

2021-05-20 14:45 UTC, oraNod commented on documentation/src/main/asciidoc/topics/proc_configuring_hotrod_connection_pools.adoc
> +include::config_examples/hotrod-client.properties[]
nice catch, thanks.

2021-05-20 14:46 UTC, oraNod commented on documentation/src/main/asciidoc/topics/proc_configuring_hotrod_connection_pools.adoc
> +Clients use asynchronous threads that check the validity of connections by iterating over the connection pool and sending pings to {brandname} servers.
removed this paragraph, cheers.

2021-05-20 16:02 UTC, oraNod commented on documentation/src/main/asciidoc/topics/code_examples/HotRodForceReturn.java
> +   "newValue"));
less is more

2021-05-20 16:13 UTC, oraNod commented on documentation/src/main/asciidoc/topics/code_examples/HotRodCreatePerCache.java
> +       .configurationURI(URI.create("file:/path/to/infinispan.xml"));
@pruivo I think showing `File` is better. I'm going to add that. thanks.

2021-05-20 16:14 UTC, oraNod commented on documentation/src/main/asciidoc/topics/proc_creating_caches_hotrod.adoc
> +However, {brandname} does not recommend this approach because you need to include XML directly in your Java code.
I knew I was going to get comments on this one :laughing: I'll reword this

2021-05-20 16:20 UTC, oraNod commented on documentation/src/main/asciidoc/topics/con_hotrod_request_balancing.adoc
> +Clients that use topology-aware intelligence use request balancing for all requests. The default balancing strategy is round-robin, so topology-aware clients always send requests to {brandname} Serve
Can we just reduce it down to "Hot Rod Java clients use request balancing for all requests"?

2021-05-20 16:59 UTC, pruivo commented on documentation/src/main/asciidoc/topics/con_hotrod_request_balancing.adoc
> +Clients that use topology-aware intelligence use request balancing for all requests. The default balancing strategy is round-robin, so topology-aware clients always send requests to {brandname} Serve
probably would say:
`Clients that use basic or topology-aware intelligence use request balancing for all requests. Clients using hash-distribution-aware intelligence send the request to the node that stores the key and fallbacks to request balancing if this node fails to reply. The default balancing strategy...`

BTW, the section before (1.1.1 Client Intelligence) is missing information on how to configure the client intelligence :) and, if possible, add the word `Intelligence to the intelligence names.

2021-05-20 19:06 UTC, oraNod commented on documentation/src/main/asciidoc/topics/con_xsite_state_transfer.adoc
> +====
@pruivo Hey I hope it's ok to be a little bit bold and sneak this in here. We discussed the two conditions (jgroups + infinispan) that need to be met before state transfer is triggered when sites come back online. I changed the wording a little. Hopefully didn't alter meaning. :grin:

2021-05-21 09:41 UTC, pruivo requested changes

2021-05-21 09:41 UTC, pruivo commented on documentation/src/main/asciidoc/topics/con_hotrod_request_balancing.adoc
> +* `infinispan.client.hotrod.request_balancing_strategy` in `hotrod-client.properties`.
put some example instead? wdyt?

```
ConfigurationBuilder clientBuilder = new ConfigurationBuilder();
clientBuilder.addServer()
              .host("127.0.0.1")
              .port(11222)
              .balancingStrategy(new MyCustomBalancingStrategy())
```
`infinispan.client.hotrod.request_balancing_strategy=my.package.MyCustomBalancingStrategy`

2021-05-21 09:41 UTC, pruivo commented on documentation/src/main/asciidoc/topics/code_examples/HotRodClientInstance.java
> +         .port(ConfigurationProperties.DEFAULT_HOTROD_PORT)
it is missing `192.0.2.0:11222`
the URI example has 2 servers and the `hotrod-client.properties` also has 2 servers.

2021-05-21 10:41 UTC, oraNod commented on documentation/src/main/asciidoc/topics/con_hotrod_request_balancing.adoc
> +Clients that use distribution-aware intelligence use request balancing only for failed requests.
bah. fixed.

2021-05-21 10:42 UTC, oraNod commented on documentation/src/main/asciidoc/topics/code_examples/RequestBalancing.java
> +// Connect to the {brandname} cluster
Need to add `subs=attributes+` to the code block, which I thought I did when I added the variable but I guess not. thanks for catching this.

2021-05-21 15:04 UTC, pruivo approved these changes

2021-05-25 14:14 UTC, merged

2021-05-25 14:14 UTC, ryanemerson commented
Thanks @oraNod