ISPN-13099 Support authentication for all commands in CLI
infinispan/infinispan pull request #9373
Opened 2021-06-14 14:01 UTC by diegolovison

https://issues.redhat.com/browse/ISPN-13099

2021-06-17 10:50 UTC, oraNod requested changes

2021-06-17 10:50 UTC, oraNod commented on cli/src/main/java/org/infinispan/cli/commands/CliCommand.java
> +   @Option(description = "A connection URL. Use '-' to connect to http://localhost:11222")
```suggestion
   @Option(description = "Specifies the URL for the server connection. Use '-' to connect to http://localhost:11222")
```

2021-06-17 10:50 UTC, oraNod commented on cli/src/main/java/org/infinispan/cli/commands/CliCommand.java
> +   @Option(hasValue = false, description = "Whether to trust all certificates", name = "trustall")
```suggestion
   @Option(hasValue = false, description = "Trusts all certificates as valid server identities.", name = "trustall")
```

2021-06-17 10:50 UTC, oraNod commented on cli/src/main/java/org/infinispan/cli/commands/CliCommand.java
> +   @Option(completer = FileOptionCompleter.class, name = "truststore", description = "A truststore to use when connecting to SSL/TLS-enabled servers")
```suggestion
   @Option(completer = FileOptionCompleter.class, name = "truststore", description = "Specifies a trust store that contains SSL/TLS certificates to verify server identities.")
```

2021-06-17 10:50 UTC, oraNod commented on cli/src/main/java/org/infinispan/cli/commands/CliCommand.java
> +   @Option(name = "truststore-password", description = "The password for the truststore")
```suggestion
   @Option(name = "truststore-password", description = "Specifies the password for the trust store.")
```

2021-06-17 12:15 UTC, oraNod approved these changes
LGTM

2021-06-18 14:25 UTC, pruivo commented
-1 for this PR for 2,5 reasons
* commands that don't need a "connection" (example `user`, `patch`, `cd`, etc) are affected as well. I mean, this makes no sense
```
[pedro-desktop-51675@cluster//containers/default]> disconnect --connect=http://127.0.0.1:11222
Username: pedro
Password: *****
[disconnected]> 
```
* if `AUTOCONNECT_URL`is set, it creates a new connection for each command (even `cd`)
* the issue is in the parser that ignores the args if you use an option

2021-06-18 16:27 UTC, diegolovison commented
* commands that don't need a "connection"
```
[disconnected]> connect
Username: admin
Password: *****
[dlovison-mac-43286@cluster//containers/default]> disconnect
[disconnected]> 
```
it works without the `connect` attribute

2021-06-18 16:33 UTC, tristantarrant commented
I have spoken to Stale on how to implement this properly (i.e. multiple commands on the CLI). It requires some interaction with the parser

2021-06-18 16:34 UTC, tristantarrant commented
My proposed solution would allow for things like:
`cli connect -u username -p password shutdown`

2021-06-18 16:57 UTC, diegolovison commented
Why not?
The `--connect` should go in the end. Is this the problem?
```
(base) dlovison@dlovison-mac bin % ./cli.sh shutdown server --connect http://admin:admin@127.0.0.1:11222 
(base) dlovison@dlovison-mac bin % 
```

2021-06-18 17:17 UTC, pruivo commented
the problem, IMO of course, is that it causes confusion when run in interactive since the autocompletion adds the `--connect` when you look for help

2021-09-20 12:46 UTC, tristantarrant commented
And, to make matters worse: graalvm's native-image completely messes up inherited fields, making all this pointless

2021-09-21 16:16 UTC, tristantarrant commented
I'd like to close this since we'll move away from aesh towards picocli

2021-09-21 16:17 UTC, closed without merging