[12.1] ISPN-13014 LDAP identity recursive search
infinispan/infinispan pull request #9378
Opened 2021-06-16 12:50 UTC by tristantarrant

https://issues.redhat.com/browse/ISPN-13014

2021-06-17 11:02 UTC, oraNod requested changes

2021-06-17 11:02 UTC, oraNod commented on server/runtime/src/main/resources/schema/infinispan-server-12.1.xsd
> +               The LDAP filter for getting identity by name.
```suggestion
               Specifies the LDAP filter that retrieves an identity by name.
```

2021-06-17 11:02 UTC, oraNod commented on server/runtime/src/main/resources/schema/infinispan-server-12.1.xsd
> +               The string "{0}" will be replaced by the searched identity name and the "rdn_identifier" will be the value of the "rdn-identifier" attribute.
```suggestion
               In the default value, "{0}" is replaced with the searched identity name and "rdn_identifier" is replaced with the value of the "rdn-identifier" attribute.
```

2021-06-17 11:02 UTC, oraNod commented on server/runtime/src/main/resources/schema/infinispan-server-12.1.xsd
> +               Indicates if queries are recursive.
```suggestion
               Performs recursive queries.
```

2021-06-21 14:26 UTC, tristantarrant commented
I've squashed all of @oraNod 's doc fixes

2021-06-23 09:10 UTC, merged

2021-06-23 09:10 UTC, danberindei commented
Merged, thanks Tristan!