ISPN-13173 Fix use of SSL context in OAuth2 introspection
infinispan/infinispan pull request #9446
Opened 2021-07-16 07:02 UTC by tristantarrant

https://issues.redhat.com/browse/ISPN-13173

2021-07-16 08:24 UTC, pruivo requested changes

2021-07-16 08:24 UTC, pruivo commented on server/runtime/src/main/java/org/infinispan/server/configuration/security/OAuth2Configuration.java
> +      return new AttributeSet(KeyStoreConfiguration.class, CLIENT_ID, CLIENT_SECRET, CLIENT_SSL_CONTEXT, INTROSPECTION_URL, HOST_VERIFICATION_POLICY);
```suggestion
      return new AttributeSet(OAuth2Configuration.class, CLIENT_ID, CLIENT_SECRET, CLIENT_SSL_CONTEXT, INTROSPECTION_URL, HOST_VERIFICATION_POLICY);
```

2021-07-16 08:24 UTC, pruivo commented on server/runtime/src/main/java/org/infinispan/server/configuration/security/OAuth2ConfigurationBuilder.java
>           throw Server.log.invalidUrl();
offtopic:
it would be nice to have the URL in the error message
```suggestion
         throw Server.log.invalidUrl(introspectionUrl);
```

2021-07-16 08:24 UTC, pruivo commented on server/runtime/src/main/java/org/infinispan/server/configuration/security/OAuth2ConfigurationBuilder.java
>           throw Server.log.invalidUrl();
offtopic:
it would be nice to have the URL in the error message
```suggestion
         throw Server.log.invalidUrl(introspectionUrl);
```

2021-07-16 08:24 UTC, pruivo commented on server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java
> +   public Server getServer(int server) {
unused?

2021-07-16 08:24 UTC, pruivo commented on server/tests/src/test/java/org/infinispan/server/test/core/KeyCloakServerRule.java
> +   private File keycloakDirectory;
nit: looks like both fields can be final.

2021-07-16 08:24 UTC, pruivo commented on server/tests/src/test/java/org/infinispan/server/test/core/KeyCloakServerRule.java
>     private FixedHostPortGenericContainer container;
nit
```suggestion
   private FixedHostPortGenericContainer<?> container;
```

2021-07-16 08:24 UTC, pruivo commented on server/tests/src/test/java/org/infinispan/server/test/core/KeyCloakServerRule.java
>        container = new FixedHostPortGenericContainer(KEYCLOAK_IMAGE);
nit
```suggestion
      container = new FixedHostPortGenericContainer<>(KEYCLOAK_IMAGE);
```

2021-07-16 10:08 UTC, pruivo commented
If I use a realm without `SSL`, I get the error  `Parameter 'sslContext' may not be null` which is not very useful IMO. See below.
```
2021-07-16 10:44:29,586 FATAL (main) [org.infinispan.SERVER] ISPN080028: Infinispan Server failed to start java.lang.IllegalArgumentException: Parameter 'sslContext' may not be null
	at org.wildfly.common.Assert.checkNotNullParamChecked(Assert.java:71)
	at org.wildfly.common.Assert.checkNotNullParam(Assert.java:49)
	at org.wildfly.security.auth.realm.token.validator.OAuth2IntrospectValidator.<init>(OAuth2IntrospectValidator.java:78)
	at org.wildfly.security.auth.realm.token.validator.OAuth2IntrospectValidator$Builder.build(OAuth2IntrospectValidator.java:285)
	at org.infinispan.server.configuration.security.TokenRealmConfigurationBuilder.build(TokenRealmConfigurationBuilder.java:76)
```

I made a small PoC for a "better" error message (Added `getName()` to `RealmConfigurationBuilder`)

```java
OAuth2IntrospectValidator.Builder getValidatorBuilder() {
      try {
         URL url = new URL(attributes.attribute(OAuth2Configuration.INTROSPECTION_URL).get());
         if (url.getProtocol().equalsIgnoreCase("http")) {
            // http protocol
            return validatorBuilder;
         }
      } catch (MalformedURLException e) {
         throw Server.log.invalidUrl();
      }
      // https protocol
      if (attributes.attribute(OAuth2Configuration.CLIENT_SSL_CONTEXT).isModified()) {
         String sslRealm = attributes.attribute(OAuth2Configuration.CLIENT_SSL_CONTEXT).get();
         if (realm.realmsBuilder().getSSLContext(sslRealm) == null) {
            //TODO add to log
            throw new IllegalArgumentException("Security realm " + sslRealm + " does not have SSL enabled");
         }
         return validatorBuilder;
      }
      if (realm.getSSLContext() == null) {
         //TODO add to log
         throw new IllegalArgumentException("Security realm " + realm.getName() + " does not have SSL enabled");
      }
      return validatorBuilder;
   }
```

2021-07-16 10:14 UTC, pruivo commented
@oraNod probably worth mentioning in the docs, in section https://infinispan.org/docs/stable/titles/server/server.html#token-realms_security-realms, if the `introspection-url` is using `https`, you need to have the `<ssl>` element in the `<security-realm>` or configure another `<security-realm>` with `<ssl>` (right Tristan?)

2021-07-16 13:29 UTC, tristantarrant commented
I'd also like to have https://github.com/wildfly-security/wildfly-elytron/pull/1558 merged into Elytron so that we can properly set introspection timeouts (currently none!)

2021-07-18 15:21 UTC, tristantarrant commented
> @oraNod probably worth mentioning in the docs, in section https://infinispan.org/docs/stable/titles/server/server.html#token-realms_security-realms, if the `introspection-url` is using `https`, you need to have the `<ssl>` element in the `<security-realm>` or configure another `<security-realm>` with `<ssl>` (right Tristan?)

You need an `<ssl>` element with a `<truststore>`. I'll add some adoc once I fix the test.

2021-07-19 08:24 UTC, pruivo approved these changes
the code LGTM :)

2021-07-19 09:50 UTC, tristantarrant commented
Yeah, trying to figure out why very similar code being executed by the test to retrieve the token is hanging on the SSL handshake when validating it from Elytron...

2021-07-19 14:40 UTC, oraNod commented on server/runtime/src/main/java/org/infinispan/server/logging/Log.java
> +   @Message(value = "The security realm '%s' doesn't provide SSL capabilities", id = 80059)
```suggestion
   @Message(value = "The security realm '%s' does not provide TLS capabilities.", id = 80059)
```

2021-09-08 12:00 UTC, tristantarrant commented
This will need the client SSL context changes introduced in https://github.com/infinispan/infinispan/pull/9511

2021-09-20 11:34 UTC, pruivo commented
@tristantarrant needs rebase :)

2021-09-20 12:47 UTC, tristantarrant commented
I actually intend to rebase it on top of https://github.com/infinispan/infinispan/pull/9525 which has significant changes

2021-09-21 15:37 UTC, tristantarrant commented
Rebased

2021-09-21 16:59 UTC, pruivo approved these changes
waiting for CI

2021-09-21 17:28 UTC, oraNod commented
@tristantarrant and @pruivo I've had a look through and see the schema doc updates. They seem fine but I wanted to check if there was anything else for docs (`ssl` element needed for `truststore`). Cheers.

2021-09-21 18:03 UTC, tristantarrant commented
> @tristantarrant and @pruivo I've had a look through and see the schema doc updates. They seem fine but I wanted to check if there was anything else for docs (`ssl` element needed for `truststore`). Cheers.

@oraNod this is mostly related to client ssl connections towards token providers (e.g keycloak). The truststore stuff was already documented.

2021-09-21 19:14 UTC, oraNod commented
@tristantarrant Thanks for helping me better understand the changes.

2021-09-22 11:06 UTC, merged

2021-09-22 11:06 UTC, pruivo commented
integrated! thanks @tristantarrant !