ISPN-13444 Json to Protostream conversion does not show real error
infinispan/infinispan pull request #9627
Opened 2021-11-03 16:40 UTC by gustavonalle

https://issues.redhat.com/browse/ISPN-13444

2021-11-22 11:33 UTC, karesti commented on core/src/main/java/org/infinispan/encoding/ProtostreamTranscoder.java
> +         if (e.getMessage() != null && message.contains("Unknown type")) {
message intead of calling again e.getMessage

2021-11-22 11:36 UTC, karesti requested changes
small change

2021-11-22 16:17 UTC, gustavonalle commented
fixed and rebased @karesti

2021-11-23 12:25 UTC, karesti approved these changes

2021-11-23 16:07 UTC, merged