ISPN-13479 NPE in RemoteStore when not properly initialized
infinispan/infinispan pull request #9662
Opened 2021-11-12 18:03 UTC by diegolovison

https://issues.redhat.com/browse/ISPN-13479

2021-12-02 18:47 UTC, pruivo requested changes

2021-12-02 18:47 UTC, pruivo commented on persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java
> +         return CompletableFuture.completedFuture(false);
```suggestion
         return CompletableFutures.completedFalse();
```

2021-12-02 18:47 UTC, pruivo commented on persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java
> +         return CompletableFuture.completedFuture(null);
```suggestion
         return CompletableFutures.completedNull();
```

2021-12-06 12:52 UTC, diegolovison commented
Done

2021-12-09 11:38 UTC, pruivo approved these changes

2021-12-09 11:38 UTC, merged

2021-12-09 11:38 UTC, pruivo commented
merged! thanks @diegolovison !