ISPN-13490 HotRod 3.1 UpdateBloomFilterOperation is not documented in…
infinispan/infinispan pull request #9673
Opened 2021-11-18 19:47 UTC by wburns

… protocol guide

https://issues.redhat.com/browse/ISPN-13490

2021-11-18 20:48 UTC, oraNod requested changes
@wburns Pretty minor suggestion but looks good otherwise.

2021-11-18 20:48 UTC, oraNod commented on documentation/src/main/asciidoc/topics/hotrod_protocol.adoc
> +.update bloom filter
```suggestion
.Update bloom filter
```

2021-11-19 13:35 UTC, wburns commented
Updated to capitalize both names for bloom docs

2021-11-19 13:38 UTC, oraNod approved these changes
LGTM. Thanks @wburns

2021-11-19 13:38 UTC, merged