ISPN-13578 Workaround for Elytron not using supplied providers
infinispan/infinispan pull request #9742
Opened 2021-12-14 14:50 UTC by tristantarrant

https://issues.redhat.com/browse/ISPN-13578

2021-12-15 07:30 UTC, danberindei requested changes
I believe the `ServerConfigurationSerializerTest.testConfigurationSerialization` failures at 
https://ci.infinispan.org/job/Infinispan/job/PR-9742/1/ are related.

2021-12-15 07:30 UTC, danberindei commented on server/runtime/src/main/java/org/infinispan/server/SecurityActions.java
> +                        .Security.insertProviderAt(provider, 1);
Weird wrapping

2021-12-15 08:53 UTC, danberindei commented
There's also a thread leak failure caused by `DigestMechanismFactory` using a static `nonceManager` with `new ScheduledThreadPoolExecutor(1)` as an executor and `EmbeddedInfinispanServerDriver` disabling the `DigestMechanismFactory` shutdown:

https://ci.infinispan.org/job/Infinispan/job/PR-9742/1/testReport/junit/(root)/UNKNOWN/ThreadLeakChecker/

Tristan, maybe we should create an Elytron JIRA asking them to add a `DigestMechanismFactory` constructor that takes a custom executor?

2021-12-15 11:08 UTC, pruivo approved these changes

2021-12-15 13:08 UTC, tristantarrant commented
My Digest hack broke the Digest tests :)

2021-12-15 17:33 UTC, pruivo commented
@tristantarrant checkstyle error `EmbeddedInfinispanServerDriver.java:25:8: Unused import - org.wildfly.security.http.digest.DigestMechanismFactory. [UnusedImports]`

2021-12-16 15:42 UTC, tristantarrant commented
Tests fixed

2021-12-16 16:00 UTC, merged