ISPN-13602 Add trace logs to show server http requests and responses
infinispan/infinispan pull request #9771
Opened 2021-12-21 16:13 UTC by ryanemerson

https://issues.redhat.com/browse/ISPN-13602

2022-01-11 13:43 UTC, danberindei requested changes

2022-01-11 13:43 UTC, danberindei commented on server/rest/src/main/java/org/infinispan/rest/HttpMessageUtil.java
> +      buf.append(')');
I'm not sure any of these are interesting enough to write in the log at all, not to mention in a line by itself.
I would skip it and start directly with `appendInitialLine()`.

2022-01-11 13:43 UTC, danberindei commented on server/rest/src/main/java/org/infinispan/rest/HttpMessageUtil.java
> +         buf.append(StringUtil.NEWLINE);
We could write the newline first, then we wouldn't need to remove the last newline at the end.

2022-01-24 09:53 UTC, ryanemerson commented
@danberindei Updated

2022-02-03 09:49 UTC, merged

2022-02-03 09:49 UTC, danberindei commented
Merged, thanks Ryan!